export const strings = {
  SignIn: "Giriş Yap",
  SignUP: "Üye ol",
  SignUpsub: "Bir uygulamaya girmek için lütfen kaydolun",
  SignInsub: "Devam etmek için giriş yapın",
  Email: "E-posta",
  Password: "Şifre",
  OldPassword: "Köne Parola",
  NewPassword: "täze Parola",
  ConfirmNewPassword: "Şifre Tekrar",
  afterSigninBtnTxt: "Hesabınız yok mu?",
  afterSignUpBtnTxt: "Zaten hesabınız var mı?",
  Name: "Ad",
  Surname: "Soyad",
  CompanyType: "Şirket türü",
  Language: "Dil",
  Country: "Ülke",
  City: "Şehir",
  Company: "Şirket",
  CompanyName: "Şirket Adı",
  Change_Language: "Dili Değiştir",
  Submit: "Kaydet",
  Submit2: "Değiştir",
  PasswordVerification: "Şifre Doğrulaması",
  CreateNewPassword: "Yeni Şifre Oluştur",
  CreatePassword: "Şifre Oluştur",

  UploadVia: "Şuradan yükle...",
  Camera: "Kamera",
  Gallery: "Galeri",

  SerchTxt: "Ara",
  // Welcome: 'Hoş geldin,',
  // WelcomeBack: 'Tekrar hoşgeldiniz,',
  ForgotPassword: "Parolanızı mı unuttunuz?",
  ForgotPasswordHeader: "Parolanızı mı unuttunuz",
  EmailAddressPlaceholder: "E-posta adresinizi",
  PasswordPlaceholder: "Gir",
  OldPasswordPlaceholder: "Eski Şifre",
  NewPasswordPlaceholder: "Yeni Şifre",
  ConfirmPasswordPlaceholder: "Onay şifreniz",
  ConfirmNewPasswordPlaceholder: "Yeni Şifre Tekrar",
  CompanyTypePlaceholder: "Şirket türünü seçin",
  CompanyPlaceholder: "Şirketin",
  CompanynamePlaceholder: "Şirket ismi",

  NamePlaceholder: "Adınız",
  SurnamePlaceholder: "Soyadınız",
  LanguagePlaceholder: "Dil Seç",
  CountryPlaceholder: "Ülke seç",

  // Titles
  ForgotPasswordTitle: "Şifrenizi mi unuttunuz",
  ResetPasswordTitle: "Şifre Yenile",
  CompanyTypeTitle: "Şirket türü",
  UpdateProfileTitle: "Profil Güncelle",
  LocationAccessTile:
    "Lütfen konum takibi için 'Daima İzin Ver' seçeneini seçiniz",
  LocationSetting: "Konum ayarları",
  BattreyOptimizationTile:
    "Lütfen batarya optimizasyonu için 'İzin ver' seçeneğini kabul ediniz",
  DisableBattery: "Batarya Optimizasyonunu Devre Dışı Bırak",
  FreightMissing: "Kargonuz kayıp",
  FreightExchange: "Yük Borsası",
  ContractedCompanyFreights: "Anlaşmalı Firma Taşımaları",

  //UpdateProfileTitle: "Profil Güncelle",
  AddTrailerTitle: "Dorse Ekle",
  NewVehicleTitle: "Yeni Araç",
  UpdateTrailerTitle: "Dorseyi Güncelle",
  UpdateDriverTitle: "Sürücüyü güncelle",
  UpdateVehicleTitle: "Aracı Güncelle",
  AddTransportTitle: "Taşıma Ekle",
  UpdateTransportTitle: "Taşımayı Güncelle",
  TransportAddedSuccess: "Taşıma Oluşturuldu",
  ContainerProposalDeletedSuccess: "Teklif Silindi",
  AddFreightTitle: "Yük Ekle",
  UpdateFreightTitle: "Yük Güncelle",
  NewPrefferedRouteTitle: "Yeni Tercih Edilen Rota",
  UpdatePrefferedRouteTitle: "Tercih Edilen Rotayı Güncelle",

  //Validation Message
  EmptyEmailAlert: "Lütfen e-posta giriniz.",
  EmailAlert: "Lütfen geçerli bir e-posta girin.",
  EmptyPasswordAlert: "Lütfen şifre giriniz.",
  EmptyConfirmPasswordAlert: "Lütfen şifreyi onaylayın.",
  UnmatchPasswordAlert: "Lütfen şifrelerinizin uyuştuğundan emin olun.",
  PasswordLengthAlert: "Şifre uzunluğunuz en az 4 en fazla 8 olmalıdır.",
  NameAlert: "Lütfen isim giriniz.",
  SurnameAlert: "Lütfen soyadınızı giriniz.",
  CompanyTypeAlert: "Lütfen şirket türünü seçin.",

  EmptyTrailerPlateNoAlert: "Lütfen dorse plaka numarasını girin.",
  SelectTrailerTypeAlert: "Lütfen dorse tipini seçin.",
  SelectTrailerSpecificationAlert: "Lütfen dorse özelliklerini seçin.",
  SelectFloorTypeAlert: "Lütfen zemin tipini Uyarı.",
  SelectPlatePictureAlert: "Lütfen plaka resmini yükleyin.",

  SelectVehicleTypeAlert: "Lütfen araç tipini Uyarı.",
  EmptyPlateNoAlert: "Lütfen Plaka Numarası Gir.",
  EmptyModelAlert: "Lütfen Model Gir.",
  SelectTIRCarnetAlert: "Lütfen T.I.R karnesi yükleyin.",
  SelectVehicleLicenceAlert: "Lütfen araç ruhsatı yükleyin.",

  EmptyMobileNoAlert: "Lütfen cep telefonu numarasını giriniz.",
  invalidMobileNoAlert: "Lütfen geçerli bir cep telefonu numarası girin.",
  SelectDriverLicenceAlert: "Lütfen sürücü ehliyetini yükleyin.",
  SelectSRCLicenceAlert: "Lütfen SRC lisansını yükleyin.",
  EmptyCountryCodeAlert: "Lütfen ülke kodunu giriniz.",

  //DrawerMenu Screen
  Home: "Anasayfa",
  Transport: "Yük",
  Map: "Harita",

  Payment: "Ödeme",
  Notification: "Bildirimler",
  ResetPassword: "Şifre Yenile",

  Driver: "Şoför",
  Vehicle: "Araç",
  Trailer: "Dorse",
  MyCard: "Benim kartım",
  Freight: "Yük",
  Bill: "Fatura",
  GPS: "GPS",
  User: "Kullanıcı",

  Settings: "Ayarlar",
  PreferredRoute: "Tercih Edilen Rota",
  PreferredRoutes: "Tercih edilen rotalar",

  Help: "Yardım",
  Logout: "Çıkış Yap",

  //Edit Profile Screen
  EditProfile: "Profil Düzenle",

  // Create/Remove Application
  CreateApplication: "Başvur",
  RemoveApplication: "Başvuruyu Kaldır",
  UpdateApplication: "Başvuruyu Güncelle",
  ViewApplication: "Başvuruyu Görüntüle",

  // Forgot Password
  Send: "Gönder",

  // Reset Password
  ConfirmPasswordLower: "Şifreyi Onayla",
  ConfirmPasswordUpper: "Şifreyi Onayla",
  PasswordChangedTitle: "şifre değişti",
  PasswordChangedMsg: "Tebrikler!! Şifrenizi başarıyla değiştirdiniz.",
  SMSSentTitle: "SMS başarıyla gönderildi",
  SMSSentMsg:
    "Doğrulama linki kayıtlı cep numaranıza gönderilmiştir. Bu linkten şifreyi değiştirebilirsiniz.",
  BackToSignIn: "Oturum Açmaya Geri Dön",

  // Elect Company Type
  TruckOwner: "Kamyon Sahibi",
  FreightOwner: "Yük Sahibi",
  Next: "Sonraki",

  // Trailer List
  Details: "Detaylar",
  Delete: "Sil",

  // Add Trailer
  TrailerPlateNo: "Dorse plaka Numarası",
  EnterPlateNo: "Plaka Numarası Gir",
  TrailerType: "Dorse Türü",
  TrailerType_TautLiner: "Tenteli Treyler",
  TrailerType_FlatBed: "Düz yatak",
  TrailerType_LowBet: "Düşük Bet",
  SelectTrailerType: "Treyler tipini seçin",

  TrailerSpecifications: "Dorse Özellikleri",
  TrailerSpecifications_RemovablePoles: "Babalar Çıkar",
  TrailerSpecifications_RemovableRoof: "Açılır Tavan",
  TrailerSpecifications_RemovableSideTent: "Yanlar Açılır",
  SelectTrailerSpecifications: "Dorse Özellikleri seç",

  FloorType: "Zemin Tipi",
  FloorType_WoodenFloor: "Tahta Zemin",
  FloorType_MetalFloor: "Metal Zemin",
  SelectFloorType: "Zemin tipini seçin",

  PlatePicture: "Plaka Fotoğrafı",
  SelectPlatePicture: "Plaka Fotoğrafı Seç",

  TrailerPicture: "Dorse Resmi",
  SelectTrailerPicture: "Dorse resmini seçin",

  Container: "Konteyner",
  TrailerContainer: "Dorse Konteyner",
  Add: "Eklemek",
  Ok: "Tamam",
  View: "Görüntüle",
  Update: "Güncelle",
  UpdateImage: "Değiştir",
  Cancel: "İptal",

  // Save Driver
  NewDriverTitle: "Yeni Şoför Oluşturma",
  UpdateDriverTitle: "Sürücüyü güncelle",
  DOB: "Doğum tarihi",
  SelectDateOfBirth: "Doğum tarihini seçin",

  MobileNo: "Cep Telefonu",
  EnterMobileNo: "Gir",

  DriverLicence: "Ehliyet",
  Preview: "Ön izleme",
  SelectDriverLicence: "Ehliyet seçin",

  SRCLicence: "SRC Lisansı",
  SelectSRCLicence: "SRC lisansı seçin",

  // Save Vehicle
  VehicleType: "Araç türü",
  SelectVehicleType: "Araç Türü Seç",
  PlateNo: "Plaka",
  EnterPlatNo: "Plaka Numarası Gir",
  Model: "Model",
  EnterModel: "Model Gir",
  Type: "Tip",

  TIRCarnet: "TIR Karnesi",
  SelectTIRCarnet: "TIR Karnesi Seç",

  SelectPlatePic: "Plaka Fotoğrafı Seç",
  VehicleLicencePicture: "Ruhsat Fotoğrafı",
  SelectVehicleLicencePic: "Ruhsat Fotoğrafı Seç",

  VehiclePicture: "Araç Resmi",
  SelectVehiclePic: "Araç resmini seçin",

  DeleteAlertTitle: "Emin misin?",
  DeleteAlertMessage: "Bu kayıtları gerçekten silmek istiyor musunuz?",
  DeleteAlertNote: "Bu işlem geri alınamaz.",

  /////// Header Status Action Items
  PassiveMode: "Yük Taşıyor",
  LookingForFreight: "Yük arıyor",
  LoadedAndOnRoad: "Çalışmıyor",

  // Save Transport
  TransportNumber: "Taşıma Numarası",
  PlannedDepartureDate: "Planlanan Ayrılış Tarihi",
  PlannedArrivalDate: "Planlanan Varış Tarihi",
  From: "İtibaren",
  FromCountry: "Ülkeden",
  FromCity: "Şehirden",
  To: "Şehire",
  ToCountry: "Ülkeye",
  ToCity: "Şehire",
  SuitableTrailer: "Dorseye uygun yükleri göster",
  ResetFilters: "Filtreleri sıfırla",

  TransportNumberPlaceholder: "Taşıma Numarasını Girin",
  PlannedDepartureDatePlaceholder: "Planlanan hareket tarihini seçin",
  PlannedArrivalDatePlaceholder: "Planlanan varış tarihini seçin",
  FromCountryPlaceholder: "Ülkeden seç",
  FromCityPlaceholder: "Şehirden seç",
  ToCountryPlaceholder: "Ülkeye seç",
  ToCityPlaceholder: "Şehir seç",
  TransportDetails: "Transporter Details",

  EmptyTransportNumberAlert: "Lütfen ulaşım numarasını giriniz.",
  SelectPlannedDepartureDateAlert: "Lütfen planlanan hareket tarihini seçin.",
  SelectPlannedArrivalDateAlert: "Lütfen planlanan varış tarihini seçin.",
  SelectFromCountryAlert: "Lütfen ülkeden seçin.",
  SelectFromCityAlert: "Lütfen şehirden Uyarı.",
  SelectToCountryAlert: "Lütfen ülkeyi seçin.",
  SelectToCityAlert: "Lütfen şehir Uyarı.",
  InvalidPlannedDepartureDateAlert:
    "Lütfen geçerli planlı hareket tarihini seçin.",
  InvalidPlannedArrivalDateAlert:
    "Lütfen geçerli planlanmış varış tarihini seçin.",

  Price: "Fiyat",
  Currency: "Para Birimi",
  Description: "Açıklama",
  CreateTransporter: "Taşıyıcı Oluştur",
  Step: "Adım",
  Of: "İle ilgili",

  // wizard page msg
  NoVehicleDataFound: "Araç verisi bulunamadı.",
  PleaseSelectTheTrailerYouDrive: "Lütfen kullandığınız dorseyi seçin",
  NoTrailerDataFound: "Dorse verisi bulunamadı.",
  PleaseSelectTheTruckYouDrive: "Lütfen kullandığınız Kamyon seçin",
  VehicleDetails: "Araç Detayları:",
  TrailerDetails: "Dorse Detayları:",
  UserDetails: "Kullanıcı Detayları:",
  Save: "Kaydet",

  SelectTheVehicle: "Aracı seçin",
  SelectTheTrailer: "Dorseyi seçin",

  // Bank Account
  BankAccountTitle: "Banka Hesabı",
  AccountHolderName: "A/c Hesap Sahibi:",
  AccountNumber: "A/c hayır.",
  AccountNo: "A/c hayır.",
  SwiftCode: "Swift Kod:",
  Explanation: "Açıklama: ",

  Username: "Kullanıcı adı",
  UsernamePlaceholder: "Kullanıcı adınızı",
  EmptyUsernameAlert: "Lütfen kullanıcı adını girin.",
  EmptyComapanynameAlert: "Lütfen Şirket adını giriniz.",
  EmptyMobilenumberAlert: "Lütfen cep telefonu numarasını giriniz.",
  Profile: "Profil",
  Profile: "Profil Güncelleme",

  Driver_Name: "Kullanıcı adı",
  Driver_email: "kullanici.user@example.com",
  Vehicle_Plate: "Araç Plakası",
  Vehicle_capacity: "Araç Kapasitesi",
  More: "Daha Fazla",
  Missing: "Eksik",
  Trailer_plate: "Dorse plakası",
  Trailer_Type: "Dorse Tipi",
  Trailer_capacity: "Dorse Kapasitesi",
  Your_route: "Rotanız",
  Your_freight: "Mevcut Yükünüz",
  showFreightInContainer: "Show freight in container",
  From_Location: "Konumdan",
  Departure_Date: "Ayrılış tarihi",
  To_Location: "Konum için",
  Arrival_Date: "Varış tarihi",
  Login_Type: "Giriş Türü",
  Primary: "Birincil Hesap Olarak Ata",

  Account_Number: "Hesap Numarası",
  swift_code: "Swift Kod",

  HolderName: "Hesap Sahibi",
  a_cNo: "Hesap Numarası",
  _explanation: "açıklama",

  E_holdername: "Hesap Sahibi Gir",
  E_acnumber: "Hesap Numarası Gir",
  E_swiftcode: "Swift Kodu Gir",
  E_explanation: "Açıklama Girin",

  //Preffered route screen
  FromCity: "Bu Şehirden",
  ToCity: "Bu Şehre",
  FromCountry: "Bu Ülkeden",
  ToCountry: "Bu Ülkeye",
  SelectCountry: "Ülke Seç",
  SelectCity: "Şehir Seç",
  Activate: "Tercih Tercih Edilen Rotalar",
  Deactive: "Tercih Tercih Edilen Rotalar",
  missingRoute: "Lütfen rotalarınızı giriniz",
  missingFreight: "Yükünüz yok",
  FromLocation: "Konumdan",
  ToLocation: "Konum için",
  No_data_found: "Veri bulunamadı",
  NoDriverCreated: "Henüz Şoför Oluşturmadınız",

  Continue: "Devam et",
  AddTransportWarning:
    "Durumunuzu değiştirmeden önce araç ve dorsenizi seçmelisiniz.",
  InitialPassword: "İlk şifre",
  Information: "Bilgi",
  LocationString:
    "Rivalog, uygulama kapalıyken veya kullanımda değilken bile yük ve kamyon takibini etkinleştirmek için konum verilerini toplar.",
  Holdon: "Devam etmek!",
  LocationAlertString:
    "Bazı ayarları etkinleştirmediğiniz sürece rotanızı sorunsuz bir şekilde izleyemiyoruz. Daha İyi bir deneyim için İzinleri her zaman İzin Ver olarak ayarlayın.",
  OpenSetting: "Ayarları aç",
  ReqMessagingPermission: "Lütfen Ayarlar'dan mesajlaşma iznini etkinleştirin",
  LocationPermissionAlways: `konum iznini "her zaman"\nolarak išaretle`,
  LocationSettings: "Konum ayarlari",
  BatteryOptDisableReq: `Lütfen pil optimizasyonu devre dışı bırakma isteğinde "İZİN VER" seçeneğini seçin`,
  DisableBatteryOptimization: "Disable Battery Optimization",
  BatteryAlertString:
    "Mükemmellik hizmeti vermek için uygulamamızın Arka Plan etkinliği erişimine ihtiyacı var. Bu nedenle, İZİN VER'e tıklayın ve Arka Plan etkinliğinin bize erişmesine Nazikçe İzin Ver'e tıklayın.",
  Location: "Konum",
  Address: "Adresler",
  Loadingaddress: "Yükleme adresi",
  Deliveraddress: "AdrTeslim adresi",
  ShowLocation: "Konumu Göster",
  GetDirection: "Yol Tarifi",
  UpdateProfileModal: "Profil Başarıyla Güncellendi !",
  Notes: "Notlar",
  ProposalScope: "Teklif Kapsamı",
  ProposalScope: "Teklif Kapsamı",
  priceRequired: "Fiyat zorunludur",
  currencyRequired: "Para birimi zorunludur",
  proposalScopeRequired: "Teklif kapsamı zorunludur",
  explanationRequired: "Açıklama zorunludur",
  completeInputs: "Zorunlu alanları doldurunuz",
  Select_truck_trailer: "Lütfen araç ve dorseyi seçiniz",
  SelectTransporter: "Taşıyıcı seçiniz",

  //Information Freight owner
  GotoWeb: "Web sitesine git",
  FreightOwnerInformation:
    "Kayıt işleminiz başarı ile tamamlandı. Ancak, mobil uygulama sadece taşıyıcı firmalar içindir. Lütfen web sayfasına gidiniz. Firmamızdan bir kişi en kısa sürede sizinle iletişim kuracaktır.",

  //Users
  UsersTitle: "Kullanıcılar",
  CreateNewUser: "Yeni Kullanıcı OLuştur",
  CountryCode: "Ülke Kodu",
  Telephone: "Telefon",
  DefaultPassword: "Geçici Şifre",

  //Create New User
  UserTitle: "Kullanıcı",
  NamePlaceholder: "Lütfen isim giriniz",
  NameRequired: "İsim zorunludur",
  SurnameRequired: "Soyisim zorunludur",
  UsernameRequired: "Kullanıcı adı zorunludur",
  EmailRequired: "Email zorunludur",
  TelephonePlaceholder: "Lütfen telefon numaranızı giriniz",
  TelephoneRequired: "Telefon numarası zorunludur",
  AddUser: "Kullanıcı Ekle",
  NoUsers: "Kullanıcı Bulunamadı",

  //Fatura Adresleri
  BillingAddressesTitle: "Fatura Adresleri",
  NoBillingAddress: "Fatura Adresi Yok",
  AddressDescription: "Adres Açıklaması",
  AddressPlaceholder: "Lütfen adres açıklamasını giriniz",
  AddressDescriptionRequired: "Adres açıklaması gerekli",
  CountryRequired: "Ülke gereklidir",
  Ülke: "Ülke",
  SelectCountryAlert: "Önce ülkeyi seçin",
  CityRequired: "Şehir gereklidir",
  District: "İlçe/Kasaba",
  DistrictRequired: "İlçe gereklidir",
  DistrictPlaceholder: "Lütfen bir bölge giriniz",
  PostCode: "Posta Kodu",
  PostRequired: "Posta Kodu gereklidir",
  Town: "Kasaba",
  TownRequired: "Şehir gereklidir",
  TownPlaceholder: "Lütfen bir şehir girin",
  Neighbourhood: "Mahalle",
  NeighbourhoodRequired: "Mahalle gereklidir",
  NeighborhoodPlaceholder: "Lütfen bir mahalle girin",

  Street: "Sokak",
  StreetRequired: "Sokak gereklidir",
  StreetPlaceholder: "Lütfen bir sokak girin",

  StreetNo: "Sokak Numarası",
  StreetNoRequired: "Sokak Numarası gerekli",
  StreetNoPlaceholder: "Lütfen bir sokak numarası giriniz",

  PostPlaceholder: "Lütfen bir posta kodu girin",
  FullAddress: "Tam Adres",
  FullAddressPlaceholder: "Lütfen tam adresinizi yazınız",
  FullAddressRequired: "Tam adres gereklidir",
  AddAddress: "Adres Ekle",
  AddNewBillingAddress: "Yeni Fatura Adresi Ekle",

  //MarkerInfoView

  LastUpdate: "Son Güncelleme :",
  DriverInfo: "SÜRÜCÜ BİLGİLERİ",
  DriverName: "Sürücü Adı :",
  PhoneNo: "Telefon No :",
  VehicleInfo: "ARAÇ BİLGİSİ",
  VehiclePlate: "Araç Plakası :",
  VehicleBrand: "Araç Markası :",
  TrailerPlate: "Dorse Plakası :",

  //Yüküm
  MyFreightTitle: "Yüküm",
  FilterByStatus: "Duruma Göre Filtrele",
  SelectAnOption: "Bir Seçenek Belirleyin",
  CreateNewLoad: "Yeni Yük Oluştur",
  NoFreights: "Yük Yok",
  Load: "Yükle",
  Deliver: "Teslim Et",

  // MyFreight // EditFreight
  DescriptionRequired: "Açıklama Gerekli",
  UploadDateAndTimeRequired: "Yükleme tarihi ve saati gerekli",
  Değer: "Değer",
  Length: "Uzunluk",
  HeightRequired: "Boy gerekli",
  WeightRequired: "Ağırlık gerekli",
  Weight: "ağırlık",
  FreightUpdateSuccess: "Yük Başarıyla Güncellendi",
  UpdateFreightFailed: "Yük Güncellemesi Başarısız Oldu",
  UploadDateAndTime: "Yükleme Tarihi ve saati",
  ArrivalDateAndTime: "Varış Tarihi ve saati",
  UploadAddress: "Yükleme Adresi",
  SelectUploadLocation: "Yükleme Konumunu Seçin",
  SelectGtipCode: "Gtip (Hs Kodu) Seç",
  ProductContainingADR1: "ADR1 İçeren Ürün",
  SelectLoadingCurrency: "Yükleme Para Birimi Seç",
  HeightValue: "Yükseklik Değeri",
  Desi: "DESI",
  Update: "Güncelle",
  Cancel: "İptal",

  //Yüklemem //YüklememYükleme

  GetFreightEditFailed: "Düzenleme İçin Yük Alımı Başarısız Oldu",
  GetFreightViewFailed: "Yük Görüntülenmesi Başarısız Oldu",
  FreightDeletedSuccess: "Yük Başarıyla Silindi",
  FreightDeletedFailed: "Yük Silinemedi",
  FreightSendApproval: "Yükü Onaya Gönder",
  FrieghtSendApprovalFailed: "Onaya gönderilemedi",

  //Şirket Bilgileri
  CompanyInfoTitle: "Şirket Bilgileri",
  CompanyNameRequired: "Şirket adı gerekli",
  TaxNumber: "Vergi numarası",
  TaxNumberRequired: "Vergi numarası gereklidir",
  TaxNumberPlaceholder: "Lütfen bir vergi numarası giriniz",
  Website: "İnternet sitesi",
  WebsiteRequired: "Web sitesi gereklidir",
  WebsitePlaceholder: "Lütfen bir web sitesi girin",
  Phone: "Telefon",
  PhoneRequired: "Telefon numarası gereklidir",
  PhonePlaceholder: "Lütfen bir telefon numarası giriniz",
  UpdateInformations: "Bilgileri Güncelle",

  // CreateNewFreight // PreviewInfo
  FreightCreatedSuccessfully: "Freight Başarıyla Oluşturuldu",
  CreateFreightFailed: "Nakliye Oluşturma Başarısız Oldu",
  UploadData: "Yükleme Tarihi",
  ArivalDate: `Varış Tarihi`,
  AddressPreferences: "Adres Tercihleri",
  UplaodAddress: "Yükleme Adresi",
  ArrivalAddress: `Varış Adresi`,
  GoodInformation: "İyi Bilgi",
  GtipCode: "Gtip (Hs Kodu)",
  WidthValue: `Genişlik Değeri`,
  GrossKG: "Brüt KG",
  StackableProduct: `İstiflenebilir Ürün`,
  LoadingCurrency: `Para Birimi Yükleniyor`,
  LenghtValue: `Uzunluk Değeri`,
  ProductContainingADRI: `ADR1 İçeren Ürün`,
  Kaydet: "Kaydet",

  //CreateNewFreight //Adım 1

  VehicleOption: "Araç Seçenekleri",
  SelectFreightType: "Kargo Tipi Seçiniz",
  LoadDescriptionRequired: "Yük açıklaması gerekli",
  LoadDescription: "Yük Açıklaması",
  EnterLoadDescription: "Yük açıklamasını girin",
  FreightTypeRequired: "Nakliye Tipi gerekli",
  FreightType: "Yük Tipi",
  TrailerType: "Dorse Türü",
  SelectTrailerType: "İlk önce Taşıma Türünü seçin",
  FloorTypeRequired: "Zemin Tipi gereklidir",
  FloorType: "Zemin Tipi",
  TransportType: "Taşıma Türü",
  TransportTypeRequired: "Taşıma Türü Gerekli",
  SelectTransportType: "Taşıma Türünü Seçin",
  TrailerKostümleştirme: "Dorse Özellikleri",
  TrailerTypeRequired: "Dorse tipi gerekli",
  SelectFloorType: "Zemin Tipini Seçin",
  TrailerCustomization: "Dorse Özelleştirme",
  TrailerYer: "Dorse özelleştirmelerini görmek için önce dorse türünü seçin.",
  ThreeStepsLeft: "3 Adım kaldı",

  //CreateNewFreight //Step2

  DepartureLocationRequired: "Gidiş lokasiyonu gerekli",
  ArrivalLocationRequired: "Varış konumu gerekli",
  FromWhereToWhere: "Nereden nereye",
  AddNewAddress: "Yeni Adres Ekle",
  DepartureLocation: "Kalkış Konumu",
  SelectDepartureLocation: "Kalkış Konumunu Seçin",
  ArrivalLocation: "Varış Konumu",
  SelectArrivalLocation: "Varış Konumunu Seçin",
  TwostepLeft: "2 adım kaldı",
  ExistingAddress:"Existing Address",
  NewAddress:"New Address",

  //CreateNewFreight // 3. Adım

  UploadDateRequired: "Yükleme Tarihi gerekli",
  LoadingTimeRequired: "Yükleme Süresi gerekli",
  ArrivalDateRequired: "Varış Tarihi gerekli",
  ArrivalTimeRequired: "Varış Zamanı gerekli",
  ArrivalTime: "Varışzamanı",
  DateAndTime: "Tarih ve Saat",
  Alert: "Şehirler arasındaki mesafe alınamadı",
  TotalDistance: "Toplam Mesafe",
  Tahmin: "Tahmin",
  UploadDate: "Yükleme Tarihi",
  SelectUploadDate: "Yükleme Tarihini Seçin",
  LoadingTime: "Yükleme Süresi",
  SelectLoadingTime: "Yükleme Süresini Seçin",
  ArrivalDate: "Varış Tarihi",
  SelectArrivalDate: "Varış Tarihini Seçin",
  TimeOfArrival: "Varış Saati",
  SelectTimeOfArrival: "Varış Zamanını Seçin",
  OneStepLeft: "1 Adım kaldı",
  Continue: "Devam",
  TurnBack: "Geri Dön",

  //CreateNewFreight // step4
  ValueRequired: "Değer gerekli",
  CurrencyRequired: "Değer gerekli",
  FreightContentTypeRequired: "Yük içerik türü gereklidir",
  PackagingTypeRequired: "Paketleme Türü gereklidir",
  LoadingTypeRequired: "Yükleme Türü gerekli",
  GtipRequired: "HS kod gereklidir",
  Gtip: "HS Kod",
  LenghtRequired: "Uzunluk gerekli",
  Lenght: "Uzunluk",
  WidthRequired: "Genişlik gerekli",
  Width: "Genişlik",
  HeightRequired: "Boy gerekli",
  Height: "Boy",
  GrossRequired: "Brüt gereklidir",
  Brüt: "Brüt",
  GoodsInfo: "Mal Bilgileri",
  Değer: "Değer",
  EnterValue: "Değer Girin",
  Currency: "Para Birimi",
  SelectCurrency: "Para Birimi Seçin",
  FreightContentType: "Yük İçerik Türü",
  SelectFreightContentType: "Yük İçerik Tipini Seçin",
  PackagingType: "Ambalaj Tipi",
  SelectPackagingType: "Paketleme Tipini Seçin",
  LoadingType: "Yükleme Türü",
  SelectLoadingType: "Yükleme Tipini Seçin",
  GripCode: "HS Kod",
  SearchGtip: "HS Kod Ara",
  LengthValue: "Uzunluk Değeri (CM)",
  EnterLenghtValue: "Uzunluk Değerini Girin",
  WidhtValue: "Genişlik Değeri (CM)",
  EnterWidthValue: "Genişlik Değerini Girin",
  HeightValue: "Yükseklik Değeri (CM)",
  EnterHeightValue: "Yükseklik Değerini Girin",
  EnterWeight: "Bir Ağırlık Girin",
  EnterDesiValue: "Desi Değerini Girin",
  LDM: "LDM",
  EnterLDMValue: "Ldm Değerini Girin",
  Not: "Not",
  EnterNote: "Notunuzu Girin",
  ProductContainingADRI: "ADR1 (Yanıcı, Tehlikeli, Kimyasal) İçeren Ürün",
  Yığınlanabilir: "Yığınlanabilir",
  LastStep: "Son Adım",
  PreviewInfo: "Önizleme Bilgileri",

  showDetail: "Ayrıntıları Göster",

  //Alt Sözleşme
  SubContract: "Alt Sözleşme",
  ApplyForContract: "Sözleşme İçin Başvur",
  subContractDelSucces: "Alt Sözleşme Başarıyla Silindi",
  subContractDelFailed: "Alt Sözleşme Silinmedi Başarısız",
  applySubContract: "Alt Sözleşme Uygula",
  applyForSubContract: "Alt Sözleşmeye Başvur",
  applyForSubContractSuccess: "Alt Sözleşme Başvurusu Başarıyla Yapıldı",
  applyForSubContractFailed: "Alt Sözleşme Başvurusu Başarısız Oldu",
  noSubContract: "Alt Sözleşme Verisi Yok",
  deleteAccount: "Hesabı Sil",
};
