export const strings = {
  SignIn: "Sign In",
  SignUP: "Sign Up",
  SignUpsub: "Please sign up to enter in an app",
  SignInsub: "Please sign in to continue",
  Email: "Email",
  Password: "Password",
  OldPassword: "Old Password",
  NewPassword: "New Password",
  ConfirmNewPassword: "Confirm New Password",
  afterSigninBtnTxt: "Don't have an account?",
  afterSignUpBtnTxt: "Already have an account?",
  Name: "Name",
  Surname: "Surname",
  CompanyType: "Company Type",
  Language: "Language",
  Country: "Country",
  City: "City",
  Company: "Company",
  CompanyName: "Company Name",
  Change_Language: "Change Language",
  Submit: "Submit",
  Submit2: "Submit",
  PasswordVerification: "Password Verification",
  CreateNewPassword: "Create New Password",
  CreatePassword: "Create Password",

  UploadVia: "Upload via...",
  Camera: "Camera",
  Gallery: "Gallery",

  SerchTxt: "Search",
  // Welcome: 'Welocome,',
  // WelcomeBack: 'Welocome Back,',
  ForgotPassword: "Forgot Password?",
  ForgotPasswordHeader: "Forgot Password",
  EmailAddressPlaceholder: "Your email address",
  PasswordPlaceholder: "Enter",
  OldPasswordPlaceholder: "Your old password",
  NewPasswordPlaceholder: "Your new password",
  ConfirmPasswordPlaceholder: "Your confirm password",
  ConfirmNewPasswordPlaceholder: "Your confirm new password",
  CompanyTypePlaceholder: "Select company type",
  CompanyPlaceholder: "Your company",
  CompanynamePlaceholder: "Your company name",

  NamePlaceholder: "Your name",
  SurnamePlaceholder: "Your surname",
  LanguagePlaceholder: "Select language",
  CountryPlaceholder: "Select country",

  // Titles
  ForgotPasswordTitle: "Forgot Password",
  ResetPasswordTitle: "Reset Password",
  CompanyTypeTitle: "Company Type",
  UpdateProfileTitle: "Update Profile",
  AddTrailerTitle: "New Trailer",
  NewDriverTitle: "New Driver",
  NewVehicleTitle: "New Vehicle",
  UpdateTrailerTitle: "Update Trailer",
  UpdateDriverTitle: "Update Driver",
  UpdateVehicleTitle: "Update Vehicle",
  AddTransportTitle: "Add Transport",
  UpdateTransportTitle: "Update Transport",
  TransportAddedSuccess: "Transport Added Successfully",
  ContainerProposalDeletedSuccess: "Proposal Deleted Successfully",
  AddFreightTitle: "Add Freight",
  UpdateFreightTitle: "Update Freight",
  NewPrefferedRouteTitle: "New Preferred Route",
  UpdatePrefferedRouteTitle: "Update Preffered Route",
  LocationAccessTile: "Please Choose 'Always Allow' for location permissions.",
  LocationSetting: "Location settings",
  BattreyOptimizationTile:
    "Please Select 'Allow' in battery optimization disable request",
  DisableBattery: "Disable Battery",
  OpenSetting: "Open Settings",
  FreightMissing: "Your Freight is missing",
  FreightExchange: "Freight Exchange",
  ContractedCompanyFreights: "Contracted Company Freights",

  //Validation Message
  EmptyEmailAlert: "Please enter email.",
  EmailAlert: "Please enter valid email.",
  EmptyPasswordAlert: "Please enter password.",
  EmptyConfirmPasswordAlert: "Please enter confirm password.",
  UnmatchPasswordAlert: "Please make sure your passwords match.",
  PasswordLengthAlert: "Your password length must be at least 4 and at most 8.",
  NameAlert: "Please enter name.",
  SurnameAlert: "Please enter surname.",
  CompanyTypeAlert: "Please select company type.",
  EmptyTrailerPlateNoAlert: "Please enter trailer plate number.",
  SelectTrailerTypeAlert: "Please select trailer type.",
  SelectTrailerSpecificationAlert: "Please select trailer specification.",
  SelectFloorTypeAlert: "Please select floor type.",
  SelectPlatePictureAlert: "Please upload plate picture.",

  SelectVehicleTypeAlert: "Please select vehicle type.",
  EmptyPlateNoAlert: "Please enter plate number.",
  EmptyModelAlert: "Please enter model.",
  SelectTIRCarnetAlert: "Please upload T.I.R carnet.",
  SelectVehicleLicenceAlert: "Please upload vehicle licence.",
  EmptyMobileNoAlert: "Please enter mobile number.",
  invalidMobileNoAlert: "Please enter valid mobile number.",
  SelectDriverLicenceAlert: "Please upload driver licence.",
  SelectSRCLicenceAlert: "Please upload SRC licence.",
  EmptyCountryCodeAlert: "Please enter country code.",

  //DrawerMenu Screen
  Home: "Home",
  Transport: "Transport",
  Map: "Map",

  More: "More",
  Payment: "Payment",
  Notification: "Notification",
  ResetPassword: "Reset password",

  Driver: "Driver",
  Vehicle: "Vehicle",
  Trailer: "Trailer",
  MyCard: "My card",
  Freight: "Freight",
  Bill: "Bill",
  GPS: "GPS",
  User: "User",

  Settings: "Settings",
  PreferredRoute: "Preferred Route",
  PreferredRoutes: "Preferred Routes",
  Help: "Help",
  Logout: "Logout",

  //Edit Profile Screen
  EditProfile: "Edit Profile",

  // Create/Remove Application
  CreateApplication: "Apply",
  UpdateApplication: "Update Proposal",
  RemoveApplication: "Remove Proposal",
  ViewApplication: "View Proposal",

  // Forgot Password
  Send: "Send",

  // Reset Password
  ConfirmPasswordLower: "Confirm password",
  ConfirmPasswordUpper: "Confirm Password",
  PasswordChangedTitle: "Password changed",
  PasswordChangedMsg:
    "Congratulations!! You’ve successfully changed your password.",
  SMSSentTitle: "SMS Sent Successfully",
  SMSSentMsg:
    "Verification link has been sent to your registered mobile number. You can change password through that link.",
  BackToSignIn: "Back to Sign In",

  // Elect Company Type
  TruckOwner: "Truck Owner",
  FreightOwner: "Freight Owner",
  Next: "Next",

  // Trailer List
  Details: "Details",
  Delete: "Delete",

  // Add Trailer
  TrailerPlateNo: "Trailer Plate No",
  EnterPlateNo: "Enter plate number",

  TrailerType_TautLiner: "Taut-Liner",
  TrailerType_FlatBed: "Flat-Bed",
  TrailerType_LowBet: "Low-Bet",

  TrailerSpecifications: "Trailer Specifications",
  TrailerSpecifications_RemovablePoles: "Removable Poles",
  TrailerSpecifications_RemovableRoof: "Removable Roof",
  TrailerSpecifications_RemovableSideTent: "Removable Side Tent",
  SelectTrailerSpecifications: "Select trailer specifications",

  FloorType_WoodenFloor: "Wooden Floor",
  FloorType_MetalFloor: "Metal Floor",

  SelectPlatePicture: "Select plate picture",

  TrailerPicture: "Trailer Picture",
  SelectTrailerPicture: "Select trailer picture",

  Container: "Container",
  TrailerContainer: "Trailer Container",
  Add: "Add",
  Ok: "OK",
  View: "View",

  UpdateImage: "Update Image",

  // Save Driver
  UpdateDriverTitle: "Update Driver",
  DOB: "Date Of Birth",
  SelectDateOfBirth: "Select date of birth",

  MobileNo: "Mobile Number",
  EnterMobileNo: "Enter",

  DriverLicence: "Driver Licence",
  SelectDriverLicence: "Select driver licence",

  SRCLicence: "SRC Licence",
  SelectSRCLicence: "Select SRC licence",

  // Save Vehicle
  VehicleType: "Vehicle Type",
  SelectVehicleType: "Select vehicle type",
  PlateNo: "Plate No",
  EnterPlatNo: "Enter plate number",
  Model: "Model",
  EnterModel: "Enter model",
  Type: "Type",
  Preview: "Preview",

  TIRCarnet: "T.I.R Carnet",
  SelectTIRCarnet: "Select T.I.R carnet",
  PlatePicture: "Plate Picture",
  SelectPlatePic: "Select plate picture",
  VehicleLicencePicture: "Vehicle Licence Picture",
  SelectVehicleLicencePic: "Select vehicle licence picture",

  VehiclePicture: "Vehicle Picture",
  SelectVehiclePic: "Select vehicle picture",

  DeleteAlertTitle: "Are you sure?",
  DeleteAlertMessage: "Do you really want to delete these record?",
  DeleteAlertNote: "This process cannot be undone.",

  /////// Header Status Action Items
  PassiveMode: "Freight carrying",
  LookingForFreight: "Looking for freight",
  LoadedAndOnRoad: "Not working",

  // Save Transport
  TransportNumber: "Transport Number",
  PlannedDepartureDate: "Planned Departure Date",
  PlannedArrivalDate: "Planned Arrival Date",
  From: "From",
  FromCountry: "From Country",
  FromCity: "From City",
  To: "To",
  ToCountry: "To Country",
  ToCity: "To City",
  SuitableTrailer: "Show suitable freights for my trailer",
  ResetFilters: "Reset Filters",
  TransportNumberPlaceholder: "Enter transport number",
  PlannedDepartureDatePlaceholder: "Select planned departure date",
  PlannedArrivalDatePlaceholder: "Select planned arrival date",
  FromCountryPlaceholder: "Select from country",
  FromCityPlaceholder: "Select from city",
  ToCountryPlaceholder: "Select to country",
  ToCityPlaceholder: "Select to city",
  TransportDetails: "Transporter Details",

  EmptyTransportNumberAlert: "Please enter transport number.",
  SelectPlannedDepartureDateAlert: "Please select planned departure date.",
  SelectPlannedArrivalDateAlert: "Please select planned arrival date.",
  SelectFromCountryAlert: "Please select from country.",
  SelectFromCityAlert: "Please select from city.",
  SelectToCountryAlert: "Please select to country.",
  SelectToCityAlert: "Please select to city.",
  InvalidPlannedDepartureDateAlert:
    "Please select valid planned departure date.",
  InvalidPlannedArrivalDateAlert: "Please select valid planned arrival date.",

  Price: "Price",
  Currency: "Price Currency",
  Description: "Description",
  CreateTransporter: "Create Transporter",
  SelectTransporter: "Select Transporter",
  Step: "Step",
  Of: "of",

  // wizard page msg
  NoVehicleDataFound: "No vehicle data found.",
  PleaseSelectTheTrailerYouDrive: "Please select the trailer you drive",
  NoTrailerDataFound: "No trailer data found.",
  PleaseSelectTheTruckYouDrive: "Please select the truck you drive",
  VehicleDetails: "Vehicle Details:",
  TrailerDetails: "Trailer Details:",
  UserDetails: "User Details:",

  SelectTheVehicle: "Select the vehicle",
  SelectTheTrailer: "Select the trailer",

  // Bank Account
  BankAccountTitle: "Bank Account",
  AccountHolderName: "A/c Holder Name:",
  AccountNumber: "A/c No.",
  AccountNo: "Account No",
  SwiftCode: "Swift code:",
  Explanation: "Explanation:",

  Username: "UserName",
  UsernamePlaceholder: "Your UserName",
  EmptyUsernameAlert: "Please enter username.",
  EmptyComapanynameAlert: "Please enter Comapany name.",
  EmptyMobilenumberAlert: "Please enter mobile number.",
  Profile: "Profile",
  ProfileUpdate: "Profile Update",

  Driver_Name: "User Name",
  Driver_email: "user.user@example.com",
  Vehicle_Plate: "Vehicle Plate",
  Select_truck_trailer: "Please Select the truck and trailer",
  Vehicle_capacity: "Vehicle capacity",
  Missing: "Missing",
  Trailer_plate: "Trailer plate",
  Trailer_Type: "Trailer Type",
  Trailer_capacity: "Trailer capacity",
  Your_route: "Your route",
  Your_freight: "Your freight",
  showFreightInContainer: "Show freight in container",
  From_Location: "From Location",
  Departure_Date: "Departure Date",
  To_Location: "To Location",
  Arrival_Date: "Arrival Date",
  Login_Type: "Login Type",
  Primary: "Set as primary account",

  Account_Number: "Account Number",
  swift_code: "Swift code",

  HolderName: "Holder name",
  a_cNo: "a/c number",
  _explanation: "explanation",

  E_holdername: "Enter holder name",
  E_acnumber: "Enter a/c number",
  E_swiftcode: "Enter swift code",
  E_explanation: "Enter Explanation",

  //Preffered route screen
  FromCity: "From City",
  ToCity: "To City",
  FromCountry: "From Country",
  ToCountry: "To Country",
  SelectCountry: "Select Country",
  SelectCity: "Select City",
  Activate: "Activate preferred route",
  Deactive: "Deactivate preferred route",
  missingRoute: "Please enter your routes",
  missingFreight: "No freight assigned",
  FromLocation: "From Location",
  ToLocation: "To Location",
  No_data_found: "No data found",
  NoDriverCreated: "No driver created yet",

  AddTransportWarning:
    "You should select your truck and trailer before change your status.",
  InitialPassword: "Initial Password",
  Information: "Information",
  LocationString:
    "Rivalog collects location data to enable freight and truck tracking even when the app is closed or not in use.",
  Holdon: "Hold on!",
  LocationAlertString:
    "We are not able to track your route Smoothly untill you didn't enable some settings. For Better experience just set Permissions to Allow all the time.",
  OpenSetting: "Open Setting",
  ReqMessagingPermission: "Please enable messaging permission from Settings",
  LocationPermissionAlways: `Please select "Always Allow"\nin Location Permissions`,
  LocationSettings: "Location Settings",
  BatteryOptDisableReq: `Please select "ALLOW" in battery optimization disable request`,
  DisableBatteryOptimization: "Disable Battery Optimization",
  BatteryAlertString:
    "Our app need Background activity access for giving excellence service. So Click on ALLOW and Kindly Allow Background activity access to us.",
  Location: "Location",
  Address: "Address",
  Loadingaddress: "Loading address",
  Deliveraddress: "Deliver address",
  ShowLocation: "Show Location",
  GetDirection: "Get Direction",
  UpdateProfileModal: "Profile Updated Successfully !",
  Notes: "Notes",
  ProposalScope: "Proposal Scope",
  priceRequired: "Price is required",
  currencyRequired: "Currency is required",
  proposalScopeRequired: "Proposal Scope is required",
  explanationRequired: "Explanation is required",
  completeInputs: "Fill out required inputs",

  //Information Freight owner
  GotoWeb: "Goto Website",
  FreightOwnerInformation:
    "Your registration is sucessfully completed. But you should go to the rivalog web page. Mobile app is only for carrier companies. A person from our company will contact you as soon as possible.",

  //Users
  UsersTitle: "Users",
  CreateNewUser: "Create New User",
  CountryCode: "Country Code",
  Telephone: "Telephone",
  DefaultPassword: "Default Password",

  //Create New User
  UserTitle: "User",
  NamePlaceholder: "Please enter name",
  NameRequired: "Name is required",
  SurnameRequired: "Surname is required",
  UsernameRequired: "Username is required",
  EmailRequired: "Email is required",
  TelephonePlaceholder: "Please enter a telephone number",
  TelephoneRequired: "Telephone number is required",
  AddUser: "Add User",
  NoUsers: "No Users",

  //Billing Addresses
  BillingAddressesTitle: "Billing Addresses",
  NoBillingAddress: "No Billing Address",
  AddressDescription: "Address Description",
  AddressPlaceholder: "Please enter address description",
  AddressDescriptionRequired: "Address description is required",
  CountryRequired: "Country is required",
  Country: "Country",
  SelectCountryAlert: "Select country first",
  CityRequired: "City is required",
  District: "District/Town",
  DistrictRequired: "District is required",
  DistrictPlaceholder: "Please enter a district",
  PostCode: "Post Code",
  PostRequired: "Post Code is required",
  Town: "Town",
  TownRequired: "Town is required",
  TownPlaceholder: "Please enter a town",
  Neighborhood: "Neighborhood",
  NeighborhoodRequired: "Neighborhood is required",
  NeighborhoodPlaceholder: "Please enter a neighborhood",
  Street: "Street",
  StreetRequired: "Street is required",
  StreetPlaceholder: "Please enter a street",

  StreetNo: "Street Number",
  StreetNoRequired: "Street Number is required",
  StreetNoPlaceholder: "Please enter a street Number",
  PostPlaceholder: "Please enter a zip code",
  FullAddress: "Full Address",
  FullAddressPlaceholder: "Please write your full address",
  FullAddressRequired: "Full address is required",
  AddAddress: "Add Address",
  AddNewBillingAddress: "Add New Billing Address",

  //MarkerInfoView

  LastUpdate: "Last Update :",
  DriverInfo: "DRIVER INFORMATIONS",
  DriverName: "Driver Name :",
  PhoneNo: "Phone No :",
  VehicleInfo: "VEHICLE INFORMATION",
  VehiclePlate: "Vehicle Plate :",
  VehicleBrand: "Vehicle Brand :",
  TrailerPlate: "Trailer Plate :",

  //MyFreight
  MyFreightTitle: "My Freight",
  FilterByStatus: "Filter By Status",
  SelectAnOption: "Select an Option",
  CreateNewLoad: "Create New Load",
  NoFreights: "No Freights",
  Load: "Load",
  Deliver: "Deliver",

  // MyFreight // EditFreight
  DescriptionRequired: "Description Required",
  UploadDateAndTimeRequired: "Upload Date and time is required",
  Value: "Value",
  Length: "Length",
  HeightRequired: "Height is required",
  WeightRequired: "Weight is required",
  Weight: "weight",
  FreightUpdateSuccess: "Freight Updated Successfully",
  UpdateFreightFailed: "Update Freight Failed",
  UploadDateAndTime: "Upload Date and time",
  ArrivalDateAndTime: "Arrival Date and time",
  UploadAddress: "Upload Address",
  SelectUploadLocation: "Select Upload Location",
  SelectGtipCode: "Select Gtip (Hs Code)",
  ProductContainingADR1: "Product Containing ADR1",
  SelectLoadingCurrency: "Select Loading Currency",
  HeightValue: "Height Value",
  Desi: "DESI",
  Update: "Update",
  Cancel: "Cancel",

  //MyFreight // MyFreightUpload

  GetFreightEditFailed: "Get Freight for Edit Failed",
  GetFreightViewFailed: "Get Freight for View Failed",
  FreightDeletedSuccess: "Freight Deleted Succussfuly",
  FreightDeletedFailed: "Frieght Delete Failed",
  FreightSendApproval: "Freight Send For Approval",
  FrieghtSendApprovalFailed: "Frieght Send for Approval Failed",

  //CompanyInfo
  CompanyInfoTitle: "Company Info",
  CompanyNameRequired: "Company name is required",
  TaxNumber: "Tax number",
  TaxNumberRequired: "Tax number is required",
  TaxNumberPlaceholder: "Please enter a tax number",
  Website: "Website",
  WebsiteRequired: "Website is required",
  WebsitePlaceholder: "Please enter a website",
  Phone: "Phone",
  PhoneRequired: "Phone number is required",
  PhonePlaceholder: "Please enter a phone number",
  UpdateInformations: "Update Information",

  // CreateNewFreight // PreviewInfo
  FreightCreatedSuccessfully: "Freight Created Successfully",
  CreateFreightFailed: "Create Freight Failed",
  UploadData: "Upload Date",
  ArivalDate: `Arrival Date`,
  AddressPreferences: "Address Preferences",
  UplaodAddress: "Upload Address",
  ArrivalAddress: `Arrival Address`,
  GoodInformation: "Good Information",
  GtipCode: "Gtip (Hs Code)",
  WidthValue: `Width Value`,
  GrossKG: "Gross KG",
  StackableProduct: `Stackable Product`,
  LoadingCurrency: `Loading Currency`,
  LenghtValue: `Lenght Value`,
  ProductContainingADRI: `Product Containing ADR1`,
  Save: "Save",

  //CreateNewFreight //Step 1

  VehicleOption: "Vehicle Options",
  SelectFreightType: "Select Freight Type",
  LoadDescriptionRequired: "Load description is required",
  LoadDescription: "Load Description",
  EnterLoadDescription: "Enter load description",
  FreightTypeRequired: "Freight Type is required",
  FreightType: "Freight Type",
  TransportTypeRequired: "Transport Type is required",
  TransportType: "Transport Type",
  SelectTransportType: "Select Transport Type",
  TrailerType: "Trailer Type",
  SelectTrailerType: "First select Transport Type",
  FloorTypeRequired: "Floor Type is required",
  FloorType: "Floor Type",
  TrailerCostumization: "Trailer Customization",
  TrailerTypeRequired: "Trailer Type is required",
  SelectFloorType: "Select Floor Type",
  TrailerCustomization: "Trailer Customization",
  TrailerPlaceholder:
    "To see the trailer customizations, first select the trailer type.",
  ThreeStepsLeft: "3 Steps left",

  //CreateNewFreight //Step2

  DepartureLocationRequired: "Departure Location is required",
  ArrivalLocationRequired: "Arrival Location is required",
  FromWhereToWhere: "From where to where",
  AddNewAddress: "Add New Address",
  DepartureLocation: "Departure Location",
  SelectDepartureLocation: "Select Departure Location",
  ArrivalLocation: "Arrival Location",
  SelectArrivalLocation: "Select Arrival Location",
  TwostepLeft: "2 Steps left",
  ExistingAddress:"Existing Address",
  NewAddress:"New Address",

  //CreateNewFreight // Step3

  UploadDateRequired: "Upload Date is required",
  LoadingTimeRequired: "Loading Time is required",
  ArrivalDateRequired: "Arrival Date is required",
  ArrivalTimeRequired: "Time of Arrival is required",
  ArrivalTime: "timeOfArrival",
  DateAndTime: "Date and Time",
  Alert: "Couldn't get the distance between the cities",
  TotalDistance: "Total Distance",
  Estimation: "Estimation",
  UploadDate: "Upload Date",
  SelectUploadDate: "Select Upload Date",
  LoadingTime: "Loading Time",
  SelectLoadingTime: "Select Loading Time",
  ArrivalDate: "Arrival Date",
  SelectArrivalDate: "Select Arrival Date",
  TimeOfArrival: "Time of Arrival",
  SelectTimeOfArrival: "Select Time of Arrival",
  OneStepLeft: "1 Steps left",
  Continue: "Continue",
  TurnBack: "Turn Back",

  //CreateNewFreight // step4
  ValueRequired: "Value is required",
  CurrencyRequired: "Value is required",
  FreightContentTypeRequired: "Freight Content Type is required",
  PackagingTypeRequired: "Packaging Type is required",
  LoadingTypeRequired: "Loading Type is required",
  GtipRequired: "Gtip is required",
  Gtip: "Gtip",
  LenghtRequired: "Length is required",
  Lenght: "Length",
  WidthRequired: "Width is required",
  Width: "Width",
  HeightRequired: "Height is required",
  Height: "Height",
  GrossRequired: "Gross is required",
  Gross: "Gross",
  GoodsInfo: "Goods Information",
  Value: "Value",
  EnterValue: "Enter Value",
  Currency: "Currency",
  SelectCurrency: "Select Currency",
  FreightContentType: "Freight Content Type",
  SelectFreightContentType: "Select Freight Content Type",
  PackagingType: "Packaging Type",
  SelectPackagingType: "Select Packaging Type",
  LoadingType: "Loading Type",
  SelectLoadingType: "Select Loading Type",
  GripCode: "HS Code",
  SearchGtip: "Search HS Code",
  LengthValue: "Length Value (CM)",
  EnterLenghtValue: "Enter Length Value",
  WidhtValue: "Width Value (CM)",
  EnterWidthValue: "Enter Width Value",
  HeightValue: "Height Value (CM)",
  EnterHeightValue: "Enter Height Value",
  EnterWeight: "Enter a Weight",
  EnterDesiValue: "Enter Desi Value",
  LDM: "LDM",
  EnterLDMValue: "Enter Ldm Value",
  Note: "Note",
  EnterNote: "Enter Your Note",
  ProductContainingADRI:
    "Product Containing ADR1 (Flammable, Hazardous, Chemical)",
  Stackable: "Stackable",
  LastStep: "Last Step",
  PreviewInfo: "Preview Information",
  showDetail: "Show Details",

  //Sub Contract
  SubContract: "Sub Contract",
  ApplyForContract: "Apply For Contract",
  subContractDelSucces: "Sub Contract Deleted",
  subContractDelFailed: "Sub Contract Deleted Failed",
  applySubContract: "Apply Sub Contract",
  applyForSubContract: "Apply For Sub Contract",
  applyForSubContractSuccess: "Applied For Sub Contract ",
  applyForSubContractFailed: "Application For Sub Contract Failed ",
  noSubContract: "No Sub Contract Data",
  deleteAccount: "Delete Account",
};
