export const strings = {
  SignIn: "Войти",
  SignUP: "Зарегистрироваться",
  SignUpsub: "Пожалуйста, зарегистрируйтесь, чтобы войти в приложение",
  SignInsub: "Пожалуйста, войдите, чтобы продолжить",
  Email: "Электронная почта",
  Password: "Пароль",
  OldPassword: "Старый пароль",
  NewPassword: "Новый пароль",
  ConfirmNewPassword: "Подтвердите новый пароль",
  afterSigninBtnTxt: "У вас нет учетной записи?",
  afterSignUpBtnTxt: "У вас уже есть аккаунт?",
  Name: "Имя",
  Surname: "Фамилия",
  CompanyType: "Тип компании",
  Language: "Язык",
  Country: "Страна",
  City: "Город",
  Company: "Компания",
  CompanyName: "Название компании",
  Change_Language: "Изменить язык",
  Submit: "Отправить",
  Submit2: "Отправить",
  PasswordVerification: "Проверка пароля",
  CreateNewPassword: "Создать новый пароль",
  CreatePassword: "Создать пароль",
  UploadVia: "Загрузить через...",
  Camera: "Камера",
  Gallery: "Галерея",

  SerchTxt: "Поиск",
  // Добро пожаловать: 'Добро пожаловать,',
  // WelcomeBack: 'С возвращением,',
  ForgotPassword: "Забыли пароль?",
  ForgotPasswordHeader: "Забыли пароль",
  EmailAddressPlaceholder: "Ваш адрес электронной почты",
  PasswordPlaceholder: "Введите",
  OldPasswordPlaceholder: "Ваш старый пароль",
  NewPasswordPlaceholder: "Ваш новый пароль",
  ConfirmPasswordPlaceholder: "Ваш пароль для подтверждения",
  ConfirmNewPasswordPlaceholder: "Подтвердите новый пароль",
  CompanyTypePlaceholder: "Выберите тип компании",
  CompanyPlaceholder: "Ваша компания",
  CompanynamePlaceholder: "Название вашей компании",

  NamePlaceholder: "Ваше имя",
  SurnamePlaceholder: "Ваша фамилия",
  LanguagePlaceholder: "Выберите язык",
  CountryPlaceholder: "Выберите страну",

  // Заголовки
  ForgotPasswordTitle: "Забыли пароль",
  ResetPasswordTitle: "Сбросить пароль",
  CompanyTypeTitle: "Тип компании",
  UpdateProfileTitle: "Обновить профиль",
  AddTrailerTitle: "Новый трейлер",
  NewDriverTitle: "Новый драйвер",
  NewVehicleTitle: "Новый автомобиль",
  UpdateTrailerTitle: "Обновить трейлер",
  UpdateDriverTitle: "Обновить драйвер",
  UpdateVehicleTitle: "Обновить автомобиль",
  AddTransportTitle: "Добавить транспорт",
  UpdateTransportTitle: "Обновить транспорт",
  TransportAddedSuccess: "Транспорт успешно добавлен",
  ContainerProposalDeletedSuccess: "Предложение успешно удалено",
  AddFreightTitle: "Добавить груз",
  UpdateFreightTitle: "Обновить фрахт",
  NewPrefferedRouteTitle: "Новый предпочтительный маршрут",
  UpdatePrefferedRouteTitle: "Обновить предпочитаемый маршрут",
  LocationAccessTile:
    'Пожалуйста, выберите "Всегда разрешать" для разрешений местоположения.',
  LocationSetting: "Настройки местоположения",
  BattreyOptimizationTile:
    'Пожалуйста, выберите "Разрешить" в запросе на отключение оптимизации батареи',
  DisableBattery: "Отключить аккумулятор",
  OpenSetting: "Открыть настройки",
  FreightMissing: "Ваш груз отсутствует",
  FreightExchange: "фрахтовая биржа",
  ContractedCompanyFreights: "Контрактные перевозки компании",

  //Сообщение проверки
  EmptyEmailAlert: "Пожалуйста, введите адрес электронной почты.",
  EmailAlert: "Пожалуйста, введите действительный адрес электронной почты.",
  EmptyPasswordAlert: "Пожалуйста, введите пароль.",
  EmptyConfirmPasswordAlert: "Пожалуйста, введите пароль для подтверждения.",
  UnmatchPasswordAlert: "Пожалуйста, убедитесь, что ваши пароли совпадают.",
  PasswordLengthAlert:
    "Длина вашего пароля должна быть не менее 4 и не более 8.",
  NameAlert: "Пожалуйста, введите имя.",
  SurnameAlert: "Пожалуйста, введите фамилию.",
  CompanyTypeAlert: "Выберите тип компании.",
  EmptyTrailerPlateNoAlert: "Пожалуйста, введите номерной знак прицепа.",
  SelectTrailerTypeAlert: "Выберите тип трейлера.",
  SelectTrailerSpecificationAlert: "Выберите спецификацию трейлера.",
  SelectFloorTypeAlert: "Выберите тип этажа.",
  SelectPlatePictureAlert: "Пожалуйста, загрузите изображение тарелки.",

  SelectVehicleTypeAlert: "Пожалуйста, выберите тип транспортного средства.",
  EmptyPlateNoAlert: "Пожалуйста, введите номерной знак.",
  EmptyModelAlert: "Введите модель.",
  SelectTIRCarnetAlert: "Пожалуйста, загрузите книжку МДП.",
  SelectVehicleLicenceAlert:
    "Пожалуйста, загрузите лицензию на транспортное средство.",
  EmptyMobileNoAlert: "Пожалуйста, введите номер мобильного телефона.",
  invalidMobileNoAlert:
    "Пожалуйста, введите действительный номер мобильного телефона.",
  SelectDriverLicenceAlert: "Пожалуйста, загрузите водительские права.",
  SelectSRCLicenceAlert: "Пожалуйста, загрузите лицензию SRC.",
  EmptyCountryCodeAlert: "Пожалуйста, введите код страны.",

  //Экран DrawerMenu
  Home: "Дом",
  Transport: "Транспорт",
  Map: "Карта",

  More: "Еще",
  Payment: "Платеж",
  Notification: "Уведомление",
  ResetPassword: "Сбросить пароль",

  Driver: "Драйвер",
  Vehicle: "Автомобиль",
  Trailer: "Трейлер",
  MyCard: "Моя карта",
  Freight: "Грузовые перевозки",
  Bill: "Билл",
  GPS: "GPS",
  User: "Пользователь",

  Settings: "Настройки",
  PreferredRoute: "Предпочтительный маршрут",
  PreferredRoutes: "Предпочитаемые маршруты",
  Help: "Помощь",
  Logout: "Выйти",

  //Экран редактирования профиля
  EditProfile: "Редактировать профиль",

  // Создать/удалить приложение
  CreateApplication: "Применить",
  UpdateApplication: "Обновить приложение",
  RemoveApplication: "Удалить приложение",
  ViewApplication: "Просмотреть приложение",

  // Забыли пароль
  Send: "Отправить",

  // Сбросить пароль
  ConfirmPasswordLower: "Подтвердить пароль",
  ConfirmPasswordUpper: "Подтвердить пароль",
  PasswordChangedTitle: "Пароль изменен",
  PasswordChangedMsg: "Поздравляем!! Вы успешно изменили свой пароль.",
  SMSSentTitle: "SMS успешно отправлено",
  SMSSentMsg:
    "Ссылка для подтверждения отправлена на ваш зарегистрированный номер мобильного телефона. Вы можете изменить пароль по этой ссылке.",
  BackToSignIn: "Вернуться к входу",

  // Выберите тип компании
  TruckOwner: "Владелец грузовика",
  FreightOwner: "Владелец груза",
  Next: "Далее",

  // Список трейлеров
  Details: "Подробности",
  Delete: "Удалить",

  // Добавить трейлер
  TrailerPlateNo: "Номер прицепа",
  EnterPlateNo: "Введите номерной знак",

  TrailerType_TautLiner: "Натянутый лайнер",
  TrailerType_FlatBed: "Платформа",
  TrailerType_LowBet: "Малая ставка",

  TrailerSpecifications: "Характеристики трейлера",
  TrailerSpecifications_RemovablePoles: "Съемные стойки",
  TrailerSpecifications_RemovableRoof: "Съемная крыша",
  TrailerSpecifications_RemovableSideTent: "Съемная боковая палатка",
  SelectTrailerSpecifications: "Выберите характеристики прицепа",

  FloorType_WoodenFloor: "Деревянный пол",
  FloorType_MetalFloor: "Металлический пол",

  SelectPlatePicture: "Выберите изображение тарелки",

  TrailerPicture: "Фотография из трейлера",
  SelectTrailerPicture: "Выберите изображение трейлера",

  Container: "Контейнер",
  TrailerContainer: "Контейнер-трейлер",
  Add: "Добавить",
  Ok: "ОК",
  View: "Просмотр",

  UpdateImage: "Обновить изображение",

  // Сохранить драйвер
  UpdateDriverTitle: "Обновить драйвер",
  DOB: "Дата рождения",
  SelectDateOfBirth: "Выберите дату рождения",

  MobileNo: "Номер мобильного телефона",
  EnterMobileNo: "Введите",

  DriverLicence: "Водительские права",
  SelectDriverLicence: "Выберите водительское удостоверение",

  SRCLicence: "Лицензия SRC",
  SelectSRCLicence: "Выбрать лицензию SRC",

  // Сохранить автомобиль
  VehicleType: "Тип транспортного средства",
  SelectVehicleType: "Выберите тип транспортного средства",
  PlateNo: "Номер тарелки",
  EnterPlatNo: "Введите номерной знак",
  Model: "Модель",
  EnterModel: "Введите модель",
  Type: "Тип",
  Preview: "Предварительный просмотр",

  TIRCarnet: "Книжка МДП",
  SelectTIRCarnet: "Выберите книжку МДП",
  PlatePicture: "Изображение тарелки",
  SelectPlatePic: "Выберите изображение тарелки",
  VehicleLicencePicture: "Изображение лицензии транспортного средства",
  SelectVehicleLicencePic:
    "Выберите изображение номерного знака транспортного средства",

  VehiclePicture: "Изображение автомобиля",
  SelectVehiclePic: "Выберите изображение автомобиля",

  DeleteAlertTitle: "Вы уверены?",
  DeleteAlertMessage: "Вы действительно хотите удалить эти записи?",
  DeleteAlertNote: "Этот процесс нельзя отменить.",

  /////// Действия по статусу заголовка
  PassiveMode: "Перевозка грузов",
  LookingForFreight: "Ищу груз",
  LoadedAndOnRoad: "Не работает",

  // Сохранить транспорт
  TransportNumber: "Номер транспорта",
  PlannedDepartureDate: "Запланированная дата отъезда",
  PlannedArrivalDate: "Запланированная дата прибытия",
  From: "От",
  FromCountry: "Из страны",
  FromCity: "Из города",
  To: "Кому",
  ToCountry: "В страну",
  ToCity: "В город",
  SuitableTrailer: "Показать подходящие грузы для моего трейлера",
  ResetFilters: "Сбросить фильтры",
  TransportNumberPlaceholder: "Введите номер транспорта",
  PlannedDepartureDatePlaceholder: "Выберите запланированную дату отъезда",
  PlannedArrivalDatePlaceholder: "Выберите запланированную дату прибытия",
  FromCountryPlaceholder: "Выбрать из страны",
  FromCityPlaceholder: "Выбрать из города",
  ToCountryPlaceholder: "Выберите страну",
  ToCityPlaceholder: "Выберите город",
  TransportDetails: "Сведения о перевозчике",

  EmptyTransportNumberAlert: "Введите номер транспорта.",
  SelectPlannedDepartureDateAlert:
    "Пожалуйста, выберите запланированную дату отъезда.",
  SelectPlannedArrivalDateAlert:
    "Пожалуйста, выберите запланированную дату прибытия.",
  SelectFromCountryAlert: "Пожалуйста, выберите страну.",
  SelectFromCityAlert: "Пожалуйста, выберите город.",
  SelectToCountryAlert: "Выберите страну.",
  SelectToCityAlert: "Выберите город.",
  InvalidPlannedDepartureDateAlert:
    "Пожалуйста, выберите действительную запланированную дату отъезда.",
  InvalidPlannedArrivalDateAlert:
    "Пожалуйста, выберите правильную запланированную дату прибытия.",

  Price: "Цена",
  Currency: "Валюта цены",
  Description: "Описание",
  CreateTransporter: "Создать транспортер",
  SelectTransporter: "Выбрать транспортер",
  Step: "Шаг",
  Of: "из",

  // сообщение страницы мастера
  NoVehicleDataFound: "Данные о транспортном средстве не найдены.",
  PleaseSelectTheTrailerYouDrive:
    "Пожалуйста, выберите прицеп, которым вы управляете",
  NoTrailerDataFound: "Данные трейлера не найдены.",
  PleaseSelectTheTruckYouDrive:
    "Пожалуйста, выберите грузовик, которым вы управляете",
  VehicleDetails: "Информация об автомобиле:",
  TrailerDetails: "Детали трейлера:",
  UserDetails: "Информация о пользователе:",

  SelectTheVehicle: "Выберите транспортное средство",
  SelectTheTrailer: "Выберите трейлер",

  // Банковский счет
  BankAccountTitle: "Банковский счет",
  AccountHolderName: "Имя держателя кондиционера:",
  AccountNumber: "Номер кондиционера",
  AccountNo: "Номер учетной записи",
  SwiftCode: "Swift-код:",
  Explanation: "Пояснение:",

  Username: "Имя пользователя",
  UsernamePlaceholder: "Ваше имя пользователя",
  EmptyUsernameAlert: "Пожалуйста, введите имя пользователя.",
  EmptyComapanynameAlert: "Пожалуйста, введите название компании.",
  EmptyMobilenumberAlert: "Пожалуйста, введите номер мобильного телефона.",
  Profile: "Профиль",
  ProfileUpdate: "Обновление профиля",

  Driver_Name: "Имя пользователя",
  Driver_email: "user.user@example.com",
  Vehicle_Plate: "Таблица транспортного средства",
  Select_truck_trailer: "Выберите грузовик и прицеп",
  Vehicle_capacity: "Вместимость автомобиля",
  Missing: "Отсутствует",
  Trailer_plate: "Прицепная табличка",
  Trailer_Type: "Тип трейлера",
  Trailer_capacity: "Вместимость прицепа",
  Your_route: "Ваш маршрут",
  Your_freight: "Ваш груз",
  showFreightInContainer: "Показать груз в контейнере",
  From_Location: "Откуда",
  Departure_Date: "Дата отправления",
  To_Location: "В место",
  Arrival_Date: "Дата прибытия",
  Login_Type: "Тип входа",
  Primary: "Установить основной аккаунт",

  Account_Number: "Номер счета",
  swift_code: "Свифт-код",

  HolderName: "Имя держателя",
  a_cNo: "номер кондиционера",
  _explanation: "объяснение",

  E_holdername: "Введите имя держателя",
  E_acnumber: "Введите номер кондиционера",
  E_swiftcode: "Введите быстрый код",
  E_explanation: "Введите объяснение",

  //экран предпочтительного маршрута
  FromCity: "Из города",
  ToCity: "В город",
  FromCountry: "Из страны",
  ToCountry: "В страну",
  SelectCountry: "Выберите страну",
  SelectCity: "Выберите город",
  Activate: "Активировать предпочтительный маршрут",
  Deactive: "Деактивировать предпочтительный маршрут",
  missingRoute: "Пожалуйста, введите ваши маршруты",
  missingFreight: "Груз не назначен",
  FromLocation: "Из местоположения",
  ToLocation: "В место",
  No_data_found: "Данные не найдены",
  NoDriverCreated: "Драйвер еще не создан",

  AddTransportWarning:
    "Вы должны выбрать свой грузовик и прицеп перед изменением статуса.",
  InitialPassword: "Начальный пароль",
  Information: "Информация",
  LocationString:
    "Rivalog собирает данные о местоположении, чтобы обеспечить отслеживание грузов и грузовиков, даже когда приложение закрыто или не используется.",
  Holdon: "Держись!",
  LocationAlertString:
    "Мы не сможем плавно отслеживать ваш маршрут, пока вы не включите некоторые настройки. Для лучшего опыта просто установите для разрешений значение Разрешить все время.",
  OpenSetting: "Открыть настройки",
  ReqMessagingPermission:
    "Пожалуйста, включите разрешение на обмен сообщениями в настройках",
  LocationPermissionAlways: `Пожалуйста, выберите «Всегда разрешать»\n Разрешения на местоположение`,
  LocationSettings: "Настройки местоположения",
  BatteryOptDisableReq:
    'Пожалуйста, выберите "РАЗРЕШИТЬ" в запросе на отключение оптимизации батареи',
  DisableBatteryOptimization: "Отключить оптимизацию батареи",
  BatteryAlertString:
    "Нашему приложению требуется доступ к фоновой активности для предоставления качественных услуг. Поэтому нажмите «РАЗРЕШИТЬ» и любезно разрешите нам доступ к фоновой активности.",
  Location: "Местоположение",
  Address: "Адрес",
  Loadingaddress: "Загружаемый адрес",
  Deliveraddress: "Адрес доставки",
  ShowLocation: "Показать местоположение",
  GetDirection: "Получить направление",
  UpdateProfileModal: "Профиль успешно обновлен!",
  Notes: "Заметки",
  ProposalScope: "Область предложения",
  priceRequired: "Требуется цена",
  currencyRequired: "Требуется валюта",
  proposalScopeRequired: "Требуется объем предложения",
  explanationRequired: "Требуется объяснение",
  completeInputs: "Введите необходимые данные",

  //Информация грузовладельца
  GotoWeb: "Перейти на сайт",
  FreightOwnerInformation:
    "Ваша регистрация успешно завершена. Но вам следует перейти на веб-страницу соперника. Мобильное приложение предназначено только для компаний-перевозчиков. Представитель нашей компании свяжется с вами в ближайшее время.",

  //Пользователи
  UsersTitle: "Пользователи",
  CreateNewUser: "Создать нового пользователя",
  CountryCode: "Код страны",
  Telephone: "Телефон",
  DefaultPassword: "Пароль по умолчанию",

  //Создать нового пользователя
  UserTitle: "Пользователь",
  NamePlaceholder: "Пожалуйста, введите имя",
  NameRequired: "Требуется имя",
  SurnameRequired: "Требуется фамилия",
  UsernameRequired: "Требуется имя пользователя",
  EmailRequired: "Требуется электронная почта",
  TelephonePlaceholder: "Пожалуйста, введите телефон отточить номер",
  TelephoneRequired: "Требуется номер телефона",
  AddUser: "Добавить пользователя",
  NoUsers: "Нет пользователей",

  //Платежные адреса
  BillingAddressesTitle: "Платежные адреса",
  NoBillingAddress: "Нет платежного адреса",
  AddressDescription: "Описание адреса",
  AddressPlaceholder: "Пожалуйста, введите описание адреса",
  AddressDescriptionRequired: "Требуется описание адреса",
  CountryRequired: "Требуется страна",
  Country: "Страна",
  SelectCountryAlert: "Сначала выберите страну",
  CityRequired: "Требуется город",
  District: "Район/Город",
  DistrictRequired: "Требуется район",
  DistrictPlaceholder: "Введите район",
  PostCode: "Почтовый индекс",
  PostRequired: "Требуется почтовый индекс",
  Town: "Город",
  TownRequired: "Требуется город",
  TownPlaceholder: "Введите город",
  Neighborhood: "Окрестности",
  NeighborhoodRequired: "Требуется соседство",
  NeighborhoodPlaceholder: "Введите район",
  Street: "Улица",
  StreetRequired: "Требуется улица",
  StreetPlaceholder: "Введите улицу",

  StreetNo: "Номер улицы",
  StreetNoRequired: "Требуется номер улицы",
  StreetNoPlaceholder: "Пожалуйста, введите номер улицы",
  PostPlaceholder: "Пожалуйста, введите почтовый индекс",
  FullAddress: "Полный адрес",
  FullAddressPlaceholder: "Пожалуйста, напишите свой полный адрес",
  FullAddressRequired: "Требуется полный адрес",
  AddAddress: "Добавить адрес",
  AddNewBillingAddress: "Добавить новый платежный адрес",

  //MarkerInfoView

  LastUpdate: "Последнее обновление:",
  DriverInfo: "ИНФОРМАЦИЯ О ВОДИТЕЛЕ",
  DriverName: "Имя драйвера:",
  PhoneNo: "Номер телефона:",
  VehicleInfo: "ИНФОРМАЦИЯ О ТРАНСПОРТНОМ СРЕДСТВЕ",
  VehiclePlate: "Номер автомобиля:",
  VehicleBrand: "Марка автомобиля:",
  TrailerPlate: "Таблица прицепа:",

  //Мой груз
  MyFreightTitle: "Мой груз",
  FilterByStatus: "Фильтровать по статусу",
  SelectAnOption: "Выберите вариант",
  CreateNewLoad: "Создать новую загрузку",
  NoFreights: "Нет грузов",
  Load: "Загрузить",
  Deliver: "Доставить",

  // MyFreight // EditFreight
  DescriptionRequired: "Требуется описание",
  UploadDateAndTimeRequired: "Требуется дата и время загрузки",
  Value: "Значение",
  Length: "Длина",
  HeightRequired: "Требуется высота",
  WeightRequired: "Требуется вес",
  Weight: "вес",
  FreightUpdateSuccess: "Доставка успешно обновлена",
  UpdateFreightFailed: "Не удалось обновить фрахт",
  UploadDateAndTime: "Дата и время загрузки",
  ArrivalDateAndTime: "Дата и время прибытия",
  UploadAddress: "Адрес загрузки",
  SelectUploadLocation: "Выберите место загрузки",
  SelectGtipCode: "Выберите Gtip (код Hs)",
  ProductContainingADR1: "Продукт, содержащий ADR1",
  SelectLoadingCurrency: "Выберите валюту загрузки",
  HeightValue: "Значение высоты",
  Desi: "ДЕЗИ",
  Update: "Обновить",
  Cancel: "Отмена",

  //MyFreight // MyFreightUpload

  GetFreightEditFailed: "Не удалось получить фрахт для редактирования",
  GetFreightViewFailed: "Не удалось получить фрахт для просмотра",
  FreightDeletedSuccess: "Груз успешно удален",
  FreightDeletedFailed: "Ошибка удаления груза",
  FreightSendApproval: "Отправка груза на утверждение",
  FrieghtSendApprovalFailed: "Ошибка отправки запроса на утверждение",

  //Информация о компании
  CompanyInfoTitle: "Информация о компании",
  CompanyNameRequired: "Требуется название компании",
  TaxNumber: "Налоговый номер",
  TaxNumberRequired: "Требуется налоговый номер",
  TaxNumberPlaceholder: "Пожалуйста, введите налоговый номер",
  Website: "Веб-сайт",
  WebsiteRequired: "Требуется веб-сайт",
  WebsitePlaceholder: "Введите веб-сайт",
  Phone: "Телефон",
  PhoneRequired: "Требуется номер телефона",
  PhonePlaceholder: "Пожалуйста, введите номер телефона",
  UpdateInformations: "Информация об обновлении",

  // CreateNewFreight // PreviewInfo
  FreightCreatedSuccessfully: "Доставка успешно создана",
  CreateFreightFailed: "Создать фрахт не удалось",
  UploadData: "Дата загрузки",
  ArivalDate: `Дата прибытия`,
  AddressPreferences: "Настройки адреса",
  UplaodAddress: "Адрес загрузки",
  ArrivalAddress: `Адрес прибытия`,
  GoodInformation: "Полезная информация",
  GtipCode: "Gtip (код Hs)",
  WidthValue: "Значение ширины",
  GrossKG: "Брутто кг",
  StackableProduct: `Стекируемый продукт`,
  LoadingCurrency: `Загрузка валюты`,
  LenghtValue: "Значение длины",
  ProductContainingADRI: `Продукт, содержащий ADR1`,
  Save: "Сохранить",

  //CreateNewFreight //Шаг 1

  VehicleOption: "Параметры автомобиля",
  SelectFreightType: "Выберите тип груза",
  LoadDescriptionRequired: "Требуется описание загрузки",
  LoadDescription: "Загрузить описание",
  EnterLoadDescription: "Введите описание загрузки",
  FreightTypeRequired: "Требуется тип груза",
  FreightType: "Тип груза",
  TransportTypeRequired: "Требуется тип транспорта",
  TransportType: "Тип транспорта",
  SelectTransportType: "Выберите тип транспорта",
  TrailerType: "Тип трейлера",
  SelectTrailerType: "Сначала выберите тип транспорта",
  FloorTypeRequired: "Требуется тип этажа",
  FloorType: "Тип этажа",
  TrailerCostumization: "Настройка трейлера",
  TrailerTypeRequired: "Требуется тип трейлера",
  SelectFloorType: "Выберите тип этажа",
  TrailerCustomization: "Настройка трейлера",
  TrailerPlaceholder:
    "Чтобы увидеть настройки трейлера, сначала выберите тип трейлера.",
  ThreeStepsLeft: "Осталось 3 шага",

  //Создать новый груз //Шаг 2

  DepartureLocationRequired: "Требуется место отправления",
  ArrivalLocationRequired: "Требуется место прибытия",
  FromWhereToWhere: "Откуда куда",
  AddNewAddress: "Добавить новый адрес",
  DepartureLocation: "Место отправления",
  SelectDepartureLocation: "Выберите место отправления",
  ArrivalLocation: "Место прибытия",
  SelectArrivalLocation: "Выберите место прибытия",
  TwostepLeft: "Осталось 2 шага",
  ExistingAddress:"Existing Address",
  NewAddress:"New Address",

  //Создать новый груз // Шаг 3

  UploadDateRequired: "Требуется дата загрузки",
  LoadingTimeRequired: "Требуется время загрузки",
  ArrivalDateRequired: "Требуется дата прибытия",
  ArrivalTimeRequired: "Требуется время прибытия",
  ArrivalTime: "время прибытия",
  DateAndTime: "Дата и время",
  Alert: "Не удалось определить расстояние между городами",
  TotalDistance: "Общее расстояние",
  Estimation: "Оценка",
  UploadDate: "Дата загрузки",
  SelectUploadDate: "Выберите дату загрузки",
  LoadingTime: "Время загрузки",
  SelectLoadingTime: "Выберите время загрузки",
  ArrivalDate: "Дата прибытия",
  SelectArrivalDate: "Выберите дату прибытия",
  TimeOfArrival: "Время прибытия",
  SelectTimeOfArrival: "Выберите время прибытия",
  OneStepLeft: "Осталось 1 шаг",
  Continue: "Продолжить",
  TurnBack: "Повернуть назад",

  //Создать новый груз // шаг 4
  ValueRequired: "Требуется значение",
  CurrencyRequired: "Требуется значение",
  FreightContentTypeRequired: "Требуется тип грузового контента",
  PackagingTypeRequired: "Требуется тип упаковки",
  LoadingTypeRequired: "Требуется тип загрузки",
  GtipRequired: "Требуется Gtip",
  Gtip: "Гтип",
  LenghtRequired: "Требуется длина",
  Lenght: "Длина",
  WidthRequired: "Требуется ширина",
  Width: "Ширина",
  HeightRequired: "Требуется высота",
  Height: "Высота",
  GrossRequired: "Требуется брутто",
  Gross: "Брутто",
  GoodsInfo: "Информация о товарах",
  Value: "Значение",
  EnterValue: "Введите значение",
  Currency: "Валюта",
  SelectCurrency: "Выберите валюту",
  FreightContentType: "Тип грузового контента",
  SelectFreightContentType: "Выберите тип контента грузовых перевозок",
  PackagingType: "Тип упаковки",
  SelectPackagingType: "Выберите тип упаковки",
  LoadingType: "Тип загрузки",
  SelectLoadingType: "Выберите тип загрузки",
  GripCode: "Код СС",
  SearchGtip: "Поиск кода HS",
  LengthValue: "Значение длины (см)",
  EnterLenghtValue: "Введите значение длины",
  WidhtValue: "Значение ширины (см)",
  EnterWidthValue: "Введите значение ширины",
  HeightValue: "Значение роста (см)",
  EnterHeightValue: "Введите значение высоты",
  EnterWeight: "Введите вес",
  EnterDesiValue: "Введите значение Дези",
  LDM: "ЛДМ",
  EnterLDMValue: "Введите значение Ldm",
  Note: "Примечание",
  EnterNote: "Введите примечание",
  ProductContainingADRI:
    "Продукт, содержащий ADR1 (легковоспламеняющийся, опасный, химический)",
  Stackable: "Наращиваемый",
  LastStep: "Последний шаг",
  PreviewInfo: "Информация о предварительном просмотре",
  showDetail: "Показать детали",

  //Субконтракт
  SubContract: "Субконтракт",
  ApplyForContract: "Подать заявку на контракт",
  subContractDelSucces: "Субконтракт удален",
  subContractDelFailed: "Сбой удаления субконтракта",
  applySubContract: "Применить субконтракт",
  applyForSubContract: "Подать заявку на субконтракт",
  applyForSubContractSuccess: "Подана заявка на субконтракт",
  applyForSubContractFailed: "Ошибка подачи заявки на субконтракт",
  noSubContract: "Нет данных субконтракта",
  deleteAccount: "Удалить аккаунт",
};
