export const strings = {
  SignIn: "تسجيل الدخول",
  SignUP: "اشتراك",
  SignUpsub: "يرجى التسجيل للدخول في التطبيق",
  SignInsub: "من فضلك سجل دخولك للمتابعة",
  Email: "بريد الالكتروني",
  Password: "كلمة المرور",
  OldPassword: "كلمة المرور القديمة",
  NewPassword: "كلمة السر الجديدة",
  ConfirmNewPassword: "تأكيد كلمة المرور الجديدة",
  afterSigninBtnTxt: "ليس لديك حساب؟",
  afterSignUpBtnTxt: "هل لديك حساب؟",
  Name: "اسم",
  Surname: "اسم العائلة",
  CompanyType: "نوع الشركة",
  Language: "لغة",
  Country: "دولة",
  City: "مدينة",
  Submit: "يُقدِّم",

  Company: "شركة",

  UploadVia: "تحميل عبر ...",
  Camera: "الة تصوير",
  Gallery: "صالة عرض",

  SerchTxt: "ابحث هنا",
  // Welcome: 'أهلا وسهلا،',
  // WelcomeBack: 'مرحبا بعودتك،',
  ForgotPassword: "هل نسيت كلمة السر؟",
  ForgotPasswordHeader: "هل نسيت كلمة السر",
  EmailAddressPlaceholder: "عنوان بريدك الإلكتروني",
  PasswordPlaceholder: "كلمة السر خاصتك",
  OldPasswordPlaceholder: "كلمة مرورك القديمة",
  NewPasswordPlaceholder: "كلمة سرك الجديدة",
  ConfirmPasswordPlaceholder: "تأكيد كلمة المرور الخاصة بك",
  ConfirmNewPasswordPlaceholder: "تأكيد كلمة المرور الجديدة الخاصة بك",
  CompanyTypePlaceholder: "حدد نوع الشركة",
  CompanyPlaceholder: "شركتك",

  NamePlaceholder: "اسمك",
  SurnamePlaceholder: "اللقب الخاص بك",
  LanguagePlaceholder: "اختار اللغة",
  CountryPlaceholder: "حدد الدولة",

  // Titles
  ForgotPasswordTitle: "هل نسيت كلمة السر",
  ResetPasswordTitle: "إعادة تعيين كلمة المرور",
  CompanyTypeTitle: "نوع الشركة",
  UpdateProfileTitle: "تحديث الملف",
  AddTrailerTitle: "إضافة مقطورة",
  NewVehicleTitle: "مركبة جديدة",
  UpdateTrailerTitle: "تحديث المقطع الدعائي",
  UpdateDriverTitle: "تحديث السائق",
  UpdateVehicleTitle: "تحديث السيارة",
  AddTransportTitle: "أضف وسيلة نقل",
  UpdateTransportTitle: "تحديث النقل",
  TransportAddedSuccess: "Transport Added Successfully",
  ContainerProposalDeletedSuccess: "Proposal Deleted Successfully",
  AddFreightTitle: "أضف الشحن",
  UpdateFreightTitle: "تحديث الشحن",
  NewPrefferedRouteTitle: "الطريق الجديد المفضل",
  UpdatePrefferedRouteTitle: "تحديث المسار المفضل",
  LocationAccessTile: " Please Choose 'Always Allow' for location permissions.",
  LocationSetting: "Location settings",
  BattreyOptimizationTile:
    "Please Select 'Allow' in battery optimization disable request",
  DisableBattery: "Disable Battery",
  OpenSetting: "Open Settings",
  FreightMissing: "Your Freight is missing",
  FreightExchange: "Freight Exchange",
  ContractedCompanyFreights: "Contracted Company Freights",

  //Validation Message
  EmptyEmailAlert: "الرجاء إدخال البريد الإلكتروني",
  EmailAlert: "الرجاء إدخال بريد إلكتروني صحيح",
  EmptyPasswordAlert: "الرجاء إدخال كلمة المرور.",
  EmptyConfirmPasswordAlert: "الرجاء إدخال تأكيد كلمة المرور.",
  UnmatchPasswordAlert: "يرجى التأكد من تطابق كلمات السر الخاصة بك.",
  PasswordLengthAlert: "يجب أن يكون طول كلمة مرورك 4 على الأقل و 8 على الأكثر.",
  NameAlert: "الرجاء إدخال الاسم.",
  SurnameAlert: "الرجاء إدخال اللقب.",
  CompanyTypeAlert: "الرجاء تحديد نوع الشركة.",

  EmptyTrailerPlateNoAlert: "الرجاء إدخال رقم لوحة المقطورة.",
  SelectTrailerTypeAlert: "الرجاء تحديد نوع المقطورة.",
  SelectTrailerSpecificationAlert: "الرجاء تحديد مواصفات المقطورة.",
  SelectFloorTypeAlert: "الرجاء تحديد نوع الطابق.",
  SelectPlatePictureAlert: "يرجى تحميل صورة اللوحة.",

  SelectVehicleTypeAlert: "الرجاء تحديد نوع السيارة.",
  EmptyPlateNoAlert: "الرجاء إدخال رقم اللوحة.",
  EmptyModelAlert: "الرجاء إدخال النموذج.",
  SelectTIRCarnetAlert: "يرجى تحميل دفتر T.I.R.",
  SelectVehicleLicenceAlert: "الرجاء تحميل رخصة السيارة.",

  EmptyMobileNoAlert: "الرجاء إدخال رقم الهاتف المحمول.",
  invalidMobileNoAlert: "الرجاء إدخال رقم هاتف محمول صحيح.",
  SelectDriverLicenceAlert: "الرجاء تحميل رخصة القيادة.",
  SelectSRCLicenceAlert: "الرجاء تحميل ترخيص SRC.",
  EmptyCountryCodeAlert: "الرجاء إدخال رمز الدولة.",

  //DrawerMenu Screen
  Home: "مسكن",
  Transport: "المواصلات",
  Map: "خريطة",
  More: "أكثر",
  Payment: "دفع",
  Notification: "تنبيه",
  ResetPassword: "إعادة تعيين كلمة المرور",

  Driver: "سائق",
  Vehicle: "مركبة",
  Trailer: "مقطورة",
  MyCard: "بطاقتي",
  Freight: "شحن",
  Bill: "فاتورة",
  GPS: "GPS",
  User: "مستخدم",

  Settings: "إعدادات",
  PreferredRoute: "الطريق المفضل",

  Help: "يساعد",
  Logout: "تسجيل خروج",

  //Edit Profile Screen
  EditProfile: "تعديل الملف الشخصي",
  Update: "تحديث",

  // Create/Remove Application
  CreateApplication: "إنشاء التطبيق",
  RemoveApplication: "إزالة التطبيق",
  UpdateApplication: "Update Proposoal",
  ViewApplication: "View Proposoal",

  // Forgot Password
  Send: "إرسال",

  // Reset Password
  ConfirmPasswordLower: "تأكيد كلمة المرور",
  ConfirmPasswordUpper: "تأكيد كلمة المرور",
  PasswordChangedTitle: "تم تغيير كلمة السر",
  PasswordChangedMsg: "تهانينا!! لقد نجحت في تغيير كلمة مرورك.",
  BackToSignIn: "العودة إلى تسجيل الدخول",

  // Elect Company Type
  TruckOwner: "مالك الشاحنة",
  FreightOwner: "مالك الشحن",
  Next: "التالي",

  // Trailer List
  Details: "تفاصيل",
  Delete: "حذف",

  // Add Trailer
  TrailerPlateNo: "لوحة مقطورة لا",
  EnterPlateNo: "أدخل رقم اللوحة",

  TrailerType: "نوع المقطورة",
  TrailerType_TautLiner: "بطانة مشدودة",
  TrailerType_FlatBed: "سرير مسطح",
  TrailerType_LowBet: "رهان منخفض",
  SelectTrailerType: "حدد نوع المقطورة",

  TrailerSpecifications: "مواصفات المقطورة",
  TrailerSpecifications_RemovablePoles: "أقطاب قابلة للإزالة",
  TrailerSpecifications_RemovableRoof: "سقف قابل للإزالة",
  TrailerSpecifications_RemovableSideTent: "خيمة جانبية قابلة للإزالة",
  SelectTrailerSpecifications: "حدد مواصفات المقطورة",

  FloorType: "نوع الأرضية",
  FloorType_WoodenFloor: "أرضية خشبية",
  FloorType_MetalFloor: "أرضية معدنية",
  SelectFloorType: "حدد نوع الطابق",

  PlatePicture: "صورة لوحة",
  SelectPlatePicture: "حدد صورة اللوحة",

  TrailerPicture: "صورة مقطورة",
  SelectTrailerPicture: "حدد صورة مقطورة",

  Container: "وعاء",
  TrailerContainer: "حاوية مقطورة",
  Add: "يضيف",
  Ok: "موافق",
  View: "رأي",
  Update: "تحديث",
  UpdateImage: "تحديث",
  Cancel: "يلغي",

  // Save Driver
  NewDriverTitle: "سائق جديد",
  UpdateDriverTitle: "تحديث السائق",
  DOB: "تاريخ الولادة",
  SelectDateOfBirth: "حدد تاريخ الميلاد",

  MobileNo: "رقم الهاتف المحمول",
  EnterMobileNo: "أدخل رقم الهاتف المحمول",

  DriverLicence: "رخصة قيادة",
  SelectDriverLicence: "حدد رخصة القيادة",

  SRCLicence: "ترخيص SRC",
  SelectSRCLicence: "حدد ترخيص SRC",

  // Save Vehicle
  VehicleType: "نوع السيارة",
  SelectVehicleType: "حدد نوع السيارة",
  PlateNo: "لوحة لا",
  EnterPlatNo: "أدخل رقم اللوحة",
  Model: "نموذج",
  EnterModel: "أدخل النموذج",
  Type: "يكتب",
  Preview: "معاينة",

  TIRCarnet: "دفتر TIR",
  SelectTIRCarnet: "حدد دفتر النقل البري الدولي (TIR)",
  PlatePicture: "صورة لوحة",
  SelectPlatePic: "حدد صورة اللوحة",
  VehicleLicencePicture: "صورة رخصة المركبة",
  SelectVehicleLicencePic: "حدد صورة رخصة السيارة",

  VehiclePicture: "صورة السيارة",
  SelectVehiclePic: "حدد صورة السيارة",

  DeleteAlertTitle: "هل أنت واثق؟",
  DeleteAlertMessage: "هل تريد حقًا حذف هذا السجل؟",
  DeleteAlertNote: "لا يمكن التراجع عن هذه العملية.",

  /////// Header Status Action Items
  PassiveMode: "حمل البضائع",
  LookingForFreight: "أبحث عن الشحن",
  LoadedAndOnRoad: "لا يعمل",

  // Save Transport
  TransportNumber: "رقم النقل",
  PlannedDepartureDate: "تاريخ المغادرة المخطط",
  PlannedArrivalDate: "تاريخ الوصول المخطط له",
  From: "من",
  FromCountry: "من دولة",
  FromCity: "من المدينة",
  To: "إلى",
  ToCountry: "إلى البلد",
  ToCity: "إلى المدينة",
  SuitableTrailer: "Römorkuma uygun yükleri göster",
  ResetFilters: "Reset Filters",
  TransportNumberPlaceholder: "أدخل رقم النقل",
  PlannedDepartureDatePlaceholder: "حدد تاريخ المغادرة المخطط",
  PlannedArrivalDatePlaceholder: "حدد تاريخ الوصول المخطط",
  FromCountryPlaceholder: "اختر من الدولة",
  FromCityPlaceholder: "اختر من المدينة",
  ToCountryPlaceholder: "اختر البلد",
  ToCityPlaceholder: "حدد المدينة",
  TransportDetails: "Transporter Details",

  EmptyTransportNumberAlert: "الرجاء إدخال رقم النقل.",
  SelectPlannedDepartureDateAlert: "الرجاء تحديد تاريخ المغادرة المخطط.",
  SelectPlannedArrivalDateAlert: "الرجاء تحديد تاريخ الوصول المخطط.",
  SelectFromCountryAlert: "الرجاء التحديد من الدولة.",
  SelectFromCityAlert: "الرجاء التحديد من المدينة.",
  SelectToCountryAlert: "الرجاء تحديد البلد.",
  SelectToCityAlert: "الرجاء تحديد المدينة.",
  InvalidPlannedDepartureDateAlert: "يرجى تحديد تاريخ المغادرة المخطط الصحيح.",
  InvalidPlannedArrivalDateAlert: "يرجى تحديد تاريخ وصول مخطط صالح.",

  Price: "السعر",
  Currency: "السعر العملة",
  Description: "وصف",
  CreateTransporter: "إنشاء الناقل",
  SelectTransporter: "Select Transporter",
  Step: "حفظ",
  Of: "من",

  // wizard page msg
  NoVehicleDataFound: "لم يتم العثور على بيانات السيارة.",
  PleaseSelectTheTrailerYouDrive: "الرجاء تحديد المقطورة التي تقودها",
  NoVehicleDataFound: "لم يتم العثور على بيانات مقطورة.",
  PleaseSelectTheTruckYouDrive: "الرجاء تحديد الشاحنة التي تقودها",
  VehicleDetails: "تفاصيل السيارة:",
  TrailerDetails: "تفاصيل مقطورة:",
  UserDetails: "بيانات المستخدم:",
  Save: "يحفظ",

  SelectTheVehicle: "حدد السيارة",
  SelectTheTrailer: "حدد المقطورة",

  // Bank Account
  BankAccountTitle: "حساب البنك",
  AccountHolderName: "أ/ج اسم المالك:",
  AccountNumber: "أ/ج لا.",
  AccountNo: "أ/ج لا.",
  SwiftCode: "رمز السرعة:",
  Explanation: "تفسير:",

  Username: "اسم المستخدم",
  UsernamePlaceholder: "اسم المستخدم الخاص بك",
  EmptyUsernameAlert: "الرجاء إدخال اسم المستخدم.",
  EmptyMobilenumberAlert: "الرجاء إدخال رقم الهاتف المحمول.",
  Profile: "حساب تعريفي",
  ProfileUpdate: "تحديث الملف الشخصي",

  Driver_Name: "اسم االمستخدم",
  Driver_email: "user.user@example.com",
  Vehicle_Plate: "لوحة المركبة",
  Vehicle_capacity: "سعة السيارة",
  More: "أكثر",
  Missing: "مفقود",
  Trailer_plate: "لوحة مقطورة",
  Trailer_Type: "نوع المقطورة",
  Trailer_capacity: "قدرة المقطورة",
  Your_route: "مسارك",
  Your_freight: "الشحن الخاص بك",
  showFreightInContainer: "Show freight in container",
  From_Location: "من الموقع",
  Departure_Date: "تاريخ المغادرة",
  To_Location: "إلى الموقع",
  Arrival_Date: "تاريخ الوصول",
  Login_Type: "نوع تسجيل الدخول",
  Primary: "تعيين كحساب أساسي",

  Account_Number: "رقم حساب",
  swift_code: "رمز السرعة.",

  HolderName: "اسم الحامل",
  a_cNo: "رقم أ / ج",
  _explanation: "تفسير",

  E_holdername: "أدخل اسم الحامل",
  E_acnumber: "أدخل رقم a / c",
  E_swiftcode: "أدخل رمز سويفت",
  E_explanation: "أدخل الشرح",

  //Preffered route screen
  FromCity: "من المدينة",
  ToCity: "إلى المدينة",
  FromCountry: "من دولة",
  ToCountry: "إلى البلد",
  SelectCountry: "حدد الدولة",
  SelectCity: "اختر مدينة",
  Activate: "تنشيط الطريق المفضل",
  Deactive: "قم بإلغاء تنشيط المسار المفضل",
  missingRoute: "الرجاء إدخال مساراتك",
  missingFreight: "الشحن الخاص بك مفقود",
  FromLocation: "من الموقع",
  ToLocation: "إلى الموقع",
  No_data_found: "لاتوجد بيانات",
  Continue: "يكمل",
  AddTransportWarning: "يجب عليك تحديد شاحنتك ومقطورتك قبل تغيير حالتك.",
  InitialPassword: "كلمة السر الأولي",

  //Users
  UsersTitle: "Users",
  CreateNewUser: "Create New User",
  CountryCode: "Country Code",
  Telephone: "Telephone",
  DefaultPassword: "Default Password",

  //Create New User
  UserTitle: "User",
  NamePlaceholder: "Please enter name",
  NameRequired: "Nmae is required",
  SurnameRequired: "Surname is required",
  UsernameRequired: "Username is required",
  EmailRequired: "Email is required",
  TelephonePlaceholder: "Please enter a telephone number",
  TelephoneRequired: "Telephone number is required",
  AddUser: "Add User",
  NoUsers: "No Users",

  //Billing Addresses
  BillingAddressesTitle: "Billing Addresses",
  NoBillingAddress: "No Billing Address",
  AddressDescription: "Address Description",
  AddressPlaceholder: "Please enter address description",
  AddressDescriptionRequired: "Address description is required",
  CountryRequired: "Country is required",
  Country: "Country",
  SelectCountryAlert: "Select country first",
  CityRequired: "City is required",
  District: "District/Town",
  DistrictRequired: "District is required",
  DistrictPlaceholder: "Please enter a district",
  PostCode: "Post Code",
  PostRequired: "Post Code is required",
  Town: "Town",
  TownRequired: "Town is required",
  TownPlaceholder: "Please enter a town",
  Neighborhood: "Neighborhood",
  NeighborhoodRequired: "Neighborhood is required",
  NeighborhoodPlaceholder: "Please enter a neighborhood",
  Street: "Street",
  StreetRequired: "Street is required",
  StreetPlaceholder: "Please enter a street",

  StreetNo: "Street Number",
  StreetNoRequired: "Street Number is required",
  StreetNoPlaceholder: "Please enter a street Number",
  PostPlaceholder: "Please enter a zip code",
  FullAddress: "Full Address",
  FullAddressPlaceholder: "Please write your full address",
  FullAddressRequired: "Full address is required",
  AddAddress: "Add Address",
  AddNewBillingAddress: "Add New Billing Address",

  //MarkerInfoView

  LastUpdate: "Last Update :",
  DriverInfo: "DRIVER INFORMATIONS",
  DriverName: "Driver Name :",
  PhoneNo: "Phone No :",
  VehicleInfo: "VEHICLE INFORMATION",
  VehiclePlate: "Vehicle Plate :",
  VehicleBrand: "Vehicle Brand :",
  TrailerPlate: "Trailer Plate :",

  //MyFreight
  MyFreightTitle: "My Freight",
  FilterByStatus: "Filter By Status",
  SelectAnOption: "Select an Option",
  CreateNewLoad: "Create New Load",
  NoFreights: "No Freights",
  Load: "Load",
  Deliver: "Deliver",

  // MyFreight // EditFreight
  DescriptionRequired: "Description Required",
  UploadDateAndTimeRequired: "Upload Date and time is required",
  Value: "Value",
  Length: "Length",
  HeightRequired: "Height is required",
  WeightRequired: "Weight is required",
  Weight: "weight",
  FreightUpdateSuccess: "Freight Updated Successfully",
  UpdateFreightFailed: "Update Freight Failed",
  UploadDateAndTime: "Upload Date and time",
  ArrivalDateAndTime: "Arrival Date and time",
  UploadAddress: "Upload Address",
  SelectUploadLocation: "Select Upload Location",
  SelectGtipCode: "Select Gtip (Hs Code)",
  ProductContainingADR1: "Product Containing ADR1",
  SelectLoadingCurrency: "Select Loading Currency",
  HeightValue: "Height Value",
  Desi: "DESI",
  Update: "Update",
  Cancel: "Cancel",

  //MyFreight // MyFreightUpload

  GetFreightEditFailed: "Get Freight for Edit Failed",
  GetFreightViewFailed: "Get Freight for View Failed",
  FreightDeletedSuccess: "Freight Deleted Succussfuly",
  FreightDeletedFailed: "Frieght Delete Failed",
  FreightSendApproval: "Freight Send For Approval",
  FrieghtSendApprovalFailed: "Frieght Send for Approval Failed",

  //CompanyInfo
  CompanyInfoTitle: "Company Info",
  CompanyNameRequired: "Company name is required",
  TaxNumber: "Tax number",
  TaxNumberRequired: "Tax number is required",
  TaxNumberPlaceholder: "Please enter a tax number",
  Website: "Website",
  WebsiteRequired: "Website is required",
  WebsitePlaceholder: "Please enter a website",
  Phone: "Phone",
  PhoneRequired: "Phone number is required",
  PhonePlaceholder: "Please enter a phone number",
  UpdateInformations: "Update Information",

  // CreateNewFreight // PreviewInfo
  FreightCreatedSuccessfully: "Freight Created Successfully",
  CreateFreightFailed: "Create Freight Failed",
  UploadData: "Upload Date",
  ArivalDate: `Arrival Date`,
  AddressPreferences: "Address Preferences",
  UplaodAddress: "Upload Address",
  ArrivalAddress: `Arrival Address`,
  GoodInformation: "Good Information",
  GtipCode: "Gtip (Hs Code)",
  WidthValue: `Width Value`,
  GrossKG: "Gross KG",
  StackableProduct: `Stackable Product`,
  LoadingCurrency: `Loading Currency`,
  LenghtValue: `Lenght Value`,
  ProductContainingADRI: `Product Containing ADR1`,
  Save: "Save",

  //CreateNewFreight //Step 1

  VehicleOption: "Vehicle Options",
  SelectFreightType: "Select Freight Type",
  LoadDescriptionRequired: "Load description is required",
  LoadDescription: "Load Description",
  EnterLoadDescription: "Enter load description",
  FreightTypeRequired: "Freight Type is required",
  FreightType: "Freight Type",
  TrailerType: "Trailer Type",
  TransportTypeRequired: "Transport Type is required",
  TransportType: "Transport Type",
  SelectTransportType: "Select Transport Type",
  SelectTrailerType: "First select Transport Type",
  FloorTypeRequired: "Floor Type is required",
  FloorType: "Floor Type",
  TrailerCostumization: "Trailer Costumization",
  TrailerTypeRequired: "Trailer Type is required",
  SelectFloorType: "Select Floor Type",
  TrailerCustomization: "Trailer Customization",
  TrailerPlaceholder:
    "To see the trailer customizations, first select the trailer type.",
  ThreeStepsLeft: "3 Steps left",

  //CreateNewFreight //Step2

  DepartureLocationRequired: "Departure Loaction is required",
  ArrivalLocationRequired: "Arrival Location is required",
  FromWhereToWhere: "From where to where",
  AddNewAddress: "Add New Address",
  DepartureLocation: "Departure Location",
  SelectDepartureLocation: "Select Departure Location",
  ArrivalLocation: "Arrival Location",
  SelectArrivalLocation: "Select Arrival Location",
  TwostepLeft: "2 Steps left",
  ExistingAddress:"Existing Address",
  NewAddress:"New Address",

  //CreateNewFreight // Step3

  UploadDateRequired: "Upload Date is required",
  LoadingTimeRequired: "Loading Time is required",
  ArrivalDateRequired: "Arrival Date is required",
  ArrivalTimeRequired: "Time of Arrival is required",
  ArrivalTime: "timeOfArrival",
  DateAndTime: "Date and Time",
  Alert: "Couldn't get the distance between the cities",
  TotalDistance: "Total Distance",
  Estimation: "Estimation",
  UploadDate: "Upload Date",
  SelectUploadDate: "Select Upload Date",
  LoadingTime: "Loading Time",
  SelectLoadingTime: "Select Loading Time",
  ArrivalDate: "Arrival Date",
  SelectArrivalDate: "Select Arrival Date",
  TimeOfArrival: "Time of Arrival",
  SelectTimeOfArrival: "Select Time of Arrival",
  OneStepLeft: "1 Steps left",
  Continue: "Continue",
  TurnBack: "Turn Back",

  //CreateNewFreight // step4
  ValueRequired: "Value is required",
  CurrencyRequired: "Value is required",
  FreightContentTypeRequired: "Freight Content Type is required",
  PackagingTypeRequired: "Packaging Type is required",
  LoadingTypeRequired: "Loading Type is required",
  GtipRequired: "Gtip is required",
  Gtip: "Gtip",
  LenghtRequired: "Length is required",
  Lenght: "Length",
  WidthRequired: "Width is required",
  Width: "Width",
  HeightRequired: "Height is required",
  Height: "Height",
  GrossRequired: "Gross is required",
  Gross: "Gross",
  GoodsInfo: "Goods Information",
  Value: "Value",
  EnterValue: "Enter Value",
  Currency: "Currency",
  SelectCurrency: "Select Currency",
  FreightContentType: "Freight Content Type",
  SelectFreightContentType: "Select Freight Content Type",
  PackagingType: "Packaging Type",
  SelectPackagingType: "Select Packaging Type",
  LoadingType: "Loading Type",
  SelectLoadingType: "Select Loading Type",
  GripCode: "Gtip(Hs Code)",
  SearchGtip: "Search Gtip",
  LengthValue: "Length Value (CM)",
  EnterLenghtValue: "Enter Length Value",
  WidhtValue: "Width Value (CM)",
  EnterWidthValue: "Enter Width Value",
  HeightValue: "Height Value (CM)",
  EnterHeightValue: "Enter Height Value",
  EnterWeight: "Enter a Weight",
  EnterDesiValue: "Enter Desi Value",
  LDM: "LDM",
  EnterLDMValue: "Enter Ldm Value",
  Note: "Note",
  EnterNote: "Enter Your Note",
  ProductContainingADRI:
    "Product Containing ADR1 (Flammable, Hazardous, Chemical)",
  Stackable: "Stackable",
  LastStep: "Last Step",
  PreviewInfo: "Preview Information",

  Notes: "Notes",
  ProposalScope: "Proposal Scope",
  ProposalScope: "Proposal Scope",
  priceRequired: "Price is required",
  currencyRequired: "Currency is required",
  proposalScopeRequired: "Proposal Scope is required",
  explanationRequired: "Explanation is required",
  completeInputs: "Fill out required inputs",
  showDetail: "Show Details",

  //Sub Contract
  SubContract: "Sub Contract",
  ApplyForContract: "Apply For Contract",
  subContractDelSucces: "Sub Contract Deleted Successfully",
  subContractDelFailed: "Sub Contract Deleted Failed",
  applySubContract: "Apply Sub Contract",
  applyForSubContract: "Apply For Sub Contract",
  applyForSubContractSuccess: "Apply For Sub Contract Successfully ",
  applyForSubContractFailed: "Apply For Sub Contract Failed ",
  noSubContract: "No Sub Contract Data",
  deleteAccount: "Delete Account",
};
